### ISSUE TITLE
errored backend: (1): Auto111 SD-WebUI Self-Starting, automatic1111 error

### ISSUE THREAD

**Issue by rugabunda** [Stability-AI/StableSwarmUI#103]
Can't get automatic1111 to load on the backend

Get the following error:

![image](https://github.com/Stability-AI/StableSwarmUI/assets/38260267/51323cf8-db29-42c3-880d-02a5578aa2dc)

```
11:53:52.978 [Error] Final error (16) while initializing backend #1 - Auto111 SD-WebUI Self-Starting, giving up: System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at StableSwarmUI.Backends.NetworkBackendUtils.DoSelfStart(String startScript, String nameSimple, Int32 gpuId, String extraArgs, Action`1 reviseStatus, Func`2 initInternal, Action`2 takeOutput, Func`1 getStatus, Action`1 addShutdownEvent) in D:\AI\Image\StableSwarmUI\src\Backends\NetworkBackendUtils.cs:line 402
   at StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUISelfStartBackend.Init() in D:\AI\Image\StableSwarmUI\src\BuiltinExtensions\AutoWebUIBackend\AutoWebUISelfStartBackend.cs:line 35
```

**Comment by rugabunda** [comment]
SD is in a different folder than StableSwarm, is it a syntax issue? I've tried a number of different syntax for the file path without success.

**Comment by mcmonkey4eva** [comment]
Oop, that was a bug - fixed now via the commit above!

**Comment by rugabunda** [comment]
Yup, working now.  Are you planning on integrating this as an accessible tab inside your ui, similar to comfy ui?

**Comment by mcmonkey4eva** [comment]
there wouldn't really be a way to achieve a similar functionality goal. Comfy workflow editor lets you edit the workflow then use the new workflow in the swarm interface. Auto tab wouldn't be able to transfer anything back to swarm like that.
You can always just open `localhost:7821` or 22 or whichever if you just want to open the ui from the self-start auto webui
