### ISSUE TITLE
Error after changing the models path. Can't be fixed even after reinstalling :S

### ISSUE THREAD

**Issue by lanzjose** [Stability-AI/StableSwarmUI#115]
Hi I have an M1 Mac Pro. I installed StableSwarm and it went great. However, when I changed the path for models so it picked the ones i have on my A1111, it started to generate the images but in the end throwed a popup saying "Something went wrong while generating images"
The terminal gives the error I paste at the end.
I tried reverting back the changes, didn't work
I tried deleting the folder and installing it again, didn't work

Here is the error:

Error] Internal error processing T2I request: System.AggregateException: One or more errors occurred. (Connection refused (localhost:7823))
 ---> System.Net.Http.HttpRequestException: Connection refused (localhost:7823)
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at StableSwarmUI.Builtin_ScorersExtension.ScorersExtension.DoPost(String url, JObject data) in /Users/joselanz/StableSwarmUI/src/BuiltinExtensions/Scorers/ScorersExtension.cs:line 105
   at StableSwarmUI.Builtin_ScorersExtension.ScorersExtension.DoScore(Image image, String prompt, String scorer) in /Users/joselanz/StableSwarmUI/src/BuiltinExtensions/Scorers/ScorersExtension.cs:line 111
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at StableSwarmUI.Builtin_ScorersExtension.ScorersExtension.PostGenEvent(PostGenerationEventParams p) in /Users/joselanz/StableSwarmUI/src/BuiltinExtensions/Scorers/ScorersExtension.cs:line 137
   at StableSwarmUI.Text2Image.T2IEngine.<>c__DisplayClass9_1.<CreateImageTask>g__handleImage|1(Image img) in /Users/joselanz/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 153
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, CancellationToken interrupt) in /Users/joselanz/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 265
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in /Users/joselanz/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 479
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in /Users/joselanz/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 173

**Comment by mcmonkey4eva** [comment]
You have the _scorers extension_ parameters toggled on, which you probably didn't mean to do - just untoggle that and it should be fine?
