### ISSUE TITLE
Trying to install on Mac OS - ComfyUI stdout: ModuleNotFoundError: No module named 'torchvision'

### ISSUE THREAD

**Issue by rs-mobitech** [Stability-AI/StableSwarmUI#120]
Here is an error that I am receiving with the latest release of Mac OS, and Stable Swarm 

```
16:41:26.018 [Init] Initializing backend #0 - ComfyUI Self-Starting...
Cloning into 'sd-dynamic-thresholding'...
remote: Enumerating objects: 304, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 304 (delta 104), reused 116 (delta 93), pack-reused 174
Receiving objects: 100% (304/304), 1015.20 KiB | 9.95 MiB/s, done.
Resolving deltas: 100% (144/144), done.
Already up to date.
16:41:27.706 [Init] Self-Start ComfyUI on port 7821 is loading...
16:42:32.649 [Warning] ComfyUI stdout: Traceback (most recent call last):
16:42:32.649 [Warning] ComfyUI stdout:   File "/Users/richard/Projects/swarm/StableSwarmUI/dlbackend/ComfyUI/nodes.py", line 1734, in load_custom_node
16:42:32.649 [Warning] ComfyUI stdout:     module_spec.loader.exec_module(module)
16:42:32.649 [Warning] ComfyUI stdout:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
16:42:32.649 [Warning] ComfyUI stdout:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
16:42:32.649 [Warning] ComfyUI stdout:   File "/Users/richard/Projects/swarm/StableSwarmUI/dlbackend/ComfyUI/comfy_extras/nodes_upscale_model.py", line 2, in <module>
16:42:32.649 [Warning] ComfyUI stdout:     from comfy_extras.chainner_models import model_loading
16:42:32.649 [Warning] ComfyUI stdout:   File "/Users/richard/Projects/swarm/StableSwarmUI/dlbackend/ComfyUI/comfy_extras/chainner_models/model_loading.py", line 8, in <module>
16:42:32.649 [Warning] ComfyUI stdout:     from .architecture.LaMa import LaMa
16:42:32.649 [Warning] ComfyUI stdout:   File "/Users/richard/Projects/swarm/StableSwarmUI/dlbackend/ComfyUI/comfy_extras/chainner_models/architecture/LaMa.py", line 15, in <module>
16:42:32.649 [Warning] ComfyUI stdout:     from torchvision.transforms.functional import InterpolationMode, rotate
16:42:32.649 [Warning] ComfyUI stdout: ModuleNotFoundError: No module named 'torchvision'
```

Help and advice on this would be much appreciated

Also not sure if it's related but your documentation says:

> Ensure your brew packages are updated with brew update.

I think it would be good if you could list the packages needed and the command to install them. 

Note that I did try to install torch vision and I think it's now installed okay, but I still get the same errors:

```
brew list --versions torchvision
torchvision 0.15.2
```

**Comment by mcmonkey4eva** [comment]
Hi, sorry, I missed this issue - that error message is probably ignorable, but either way it should be gone for fresh installs as of https://github.com/Stability-AI/StableSwarmUI/commit/5a23492e2fa2bf1ba2e17af75dfd8de5dea412ef
