### ISSUE TITLE
Adding external ComfyUI problems

### ISSUE THREAD

**Issue by drago87** [Stability-AI/StableSwarmUI#121]
i'm using a external version of comfyui (not downloaded with StableSwarmUI)
the bat file i use to run it need to look like this
```
C:\Users\Drago87\AppData\Local\Programs\Python\Python310\python.exe -s D:\AI\ComfyUI_AMD\ComfyUI\main.py --directml 
pause
```

how do i translate that so i can run it with StableSwarmUI?
it dont have a embeded python

**Comment by mcmonkey4eva** [comment]
- add self start backend
- set path to `D:\AI\ComfyUI_AMD\ComfyUI\main.py`
- set extraargs to `--directml`

Considering you appear to be using a global python install, that should just work in theory (assuming you installed python with 'add to system path' enabled)

**Comment by drago87** [comment]
getting this error

```
21:09:26.786 [Debug] Requested generic launch of D:\AI\ComfyUI_AMD\ComfyUI\main.py on GPU 0 from ComfyUI
21:09:26.793 [Debug] (ComfyUI launch) Adding path D:\AI\ComfyUI_AMD\python_embeded
21:09:26.794 [Debug] (ComfyUI launch) Will use python: D:\AI\ComfyUI_AMD\python_embeded\python.exe
21:09:26.802 [Init] Self-Start ComfyUI on port 7821 is loading...
21:09:26.837 [Debug] ComfyUI stderr: Traceback (most recent call last):
21:09:26.840 [Debug] ComfyUI stderr:   File "ComfyUI\main.py", line 1, in <module>
21:09:26.841 [Debug] ComfyUI stderr:     import comfy.options
21:09:26.842 [Debug] ComfyUI stderr: ModuleNotFoundError: No module named 'comfy'
21:09:26.843 [Debug] Status of ComfyUI after process end is LOADING
21:09:26.845 [Info] Self-Start ComfyUI on port 7821 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
21:09:26.846 [Info] Self-Start ComfyUI on port 7821 had errors before shutdown:
ComfyUI error: Traceback (most recent call last):
ComfyUI error:   File "ComfyUI\main.py", line 1, in <module>
ComfyUI error:     import comfy.options
ComfyUI error: ModuleNotFoundError: No module named 'comfy'

21:09:27.588 [Error] [WebAPI] Error handling API request '/API/ListBackends': Request input has unknown session id
21:09:27.651 [Info] Creating new admin session for ::1
```
