### ISSUE TITLE
[Error] Internal error processing T2I request: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Slackalope1** [Stability-AI/StableSwarmUI#133]
When using a custom workflow I get the following error

`
08:02:45.977 [Error] Internal error processing T2I request: System.NullReferenceException: Object reference not set to an instance of an object.
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.<>c__DisplayClass13_1.<<GetAllImagesForHistory>g__LoadImage|0>d.MoveNext() in W:\SDXL-Apps\Swarm\2023-10-07\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 294
--- End of stack trace from previous location ---
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GetAllImagesForHistory(JToken output, CancellationToken interrupt) in W:\SDXL-Apps\Swarm\2023-10-07\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 311
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, CancellationToken interrupt) in W:\SDXL-Apps\Swarm\2023-10-07\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 265
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in W:\SDXL-Apps\Swarm\2023-10-07\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 510
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in W:\SDXL-Apps\Swarm\2023-10-07\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 178
08:02:45.977 [Debug] Refused to generate image for local: Something went wrong while generating images.
`

The base install of swarm works fine, generated and saved an image no problem. Loaded up a custom workflow that I've been using in comfy and it gives the above error.

disregard the date in the file name, I just updated swarm this morning.

Any ideas on what in my workflow could be causing this error? I have a bunch of custom_nodes going, some might be incompatible?

**Comment by mcmonkey4eva** [comment]
`disregard the date in the file name, I just updated swarm this morning.` when was 'this morning'? The relevant section of code changed earlier today and also changed yesterday.

Is this a Comfy API-by-URL or Self-Start backend? (Self-Start is the default if you didn't customize backends) (Self-Start is the better option)

Do you have any custom nodes that are saving outputs? Specifically other than the standard PreviewImage/SaveImage nodes.

Are there any errors coming out of Comfy? Since you appear to have LogLevel set to Debug they should show in console.

If none of the above leads to the answer, could you post your workflow file?

**Comment by Slackalope1** [comment]
Thanks for the reply.  This morning was a couple hours ago. 7:30am-ish eastern us time on 10-25. I will re-update again just in case.

The error happens both in the self-start and the url. Will look at my custom nodes that may be saving any outputs and look deeper in the logs.

**Comment by Slackalope1** [comment]
Well I feel dumb. There was a typo in the swarmui settings for my clipvision folder. Folder didn't exist.

Fixed the setting and all is well.
