### ISSUE TITLE
Error: Model not found.

### ISSUE THREAD

**Issue by drago87** [Stability-AI/StableSwarmUI#138]
I have added a remote ComfyUI API By URL (aka different computer)
when i have made a workflow and press the "use this workflow in generate tab" button i get a 
```
Error

Model not found.
```
and the error in the cmd promt is
`[Debug] Request for model DreamShaper_8_pruned.safetensors rejected as not found.`
and when i go to the bottom and press the model tab it is empty.
i have things in the vae, lora, embeddings and controllnet tabs and if i try to make a image from the "comfy workflow editor" tab i can make the image. the workflow i use is the you get when pressing the "load defaut" button in comfyui

**Comment by mcmonkey4eva** [comment]
install Swarm on the remote computer, and link it via the Swarm-API-Backend, that way swarm can know about the remote models and process them accordingly

**Comment by drago87** [comment]
How do i link them?

**Comment by mcmonkey4eva** [comment]
Same way you linked a comfy UI API By URL, just, use the Swarm backend instead

![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/535c07fe-7022-4df9-a2f9-0d47b06cbaf6)

**Comment by drago87** [comment]
i have installed and linked the swarm-api-backend now but i'm getting

```
[Init] Initializing backend #3 - Swarm-API-Backend...
14:34:55.069 [Error] Final error (4) while initializing backend #3 - Swarm-API-Backend, giving up: Newtonsoft.Json.JsonReaderException: Failed to parse JSON ``: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at StableSwarmUI.Utils.Utilities.ParseToJson(String input) in D:\AI\SwarmAi\StableSwarmUI\src\Utils\Utilities.cs:line 306
   at StableSwarmUI.Utils.Utilities.PostJson(HttpClient client, String url, JObject data) in D:\AI\SwarmAi\StableSwarmUI\src\Utils\Utilities.cs:line 175
   at StableSwarmUI.Backends.SwarmSwarmBackend.ValidateAndBuild() in D:\AI\SwarmAi\StableSwarmUI\src\Backends\SwarmSwarmBackend.cs:line 60
   at StableSwarmUI.Backends.SwarmSwarmBackend.Init() in D:\AI\SwarmAi\StableSwarmUI\src\Backends\SwarmSwarmBackend.cs:line 279
   at StableSwarmUI.Backends.SwarmSwarmBackend.Init() in D:\AI\SwarmAi\StableSwarmUI\src\Backends\SwarmSwarmBackend.cs:line 313
   at StableSwarmUI.Backends.BackendHandler.LoadBackendDirect(T2IBackendData data) in D:\AI\SwarmAi\StableSwarmUI\src\Backends\BackendHandler.cs:line 355
```

**Comment by mcmonkey4eva** [comment]
Are you sure that
(1) Both copies of swarm are fully up-to-date, and
(2) the address you used for the remote swarm instance is exactly correct? (If you copy/paste it into a browser, it should open the UI)

**Comment by mcmonkey4eva** [comment]
Oh, I figured out why -- that's caused by a trailing `/` in the URL - I've pushed a commit to automatically compensate for that now. (or you can just remove the `/` from the end of the URL)

**Comment by drago87** [comment]
that seamd to have fixed it and i can generate a image. 
however i get this error on the external swarmui when it is done

```
[Error] Internal error processing T2I request: System.NullReferenceException: Object reference not set to an instance of an object.
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.<>c__DisplayClass13_1.<<GetAllImagesForHistory>g__LoadImage|0>d.MoveNext() in D:\AI\SwarmAi\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 306
--- End of stack trace from previous location ---
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GetAllImagesForHistory(JToken output, CancellationToken interrupt) in D:\AI\SwarmAi\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 323
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, CancellationToken interrupt) in D:\AI\SwarmAi\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 277
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in D:\AI\SwarmAi\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 523
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in D:\AI\SwarmAi\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 220
```

**Comment by drago87** [comment]
i will close close this as it seams to work now
