### ISSUE TITLE
New Received Too Much Data Error

### ISSUE THREAD

**Issue by ataylorm** [Stability-AI/StableSwarmUI#140]
Running the latest build from yesterday I am receiving an error when doing upscale.  This workflow has been working fine for the last couple of months:

08:50:32.911 [Error] Internal error processing T2I request: System.IO.IOException: Received too much data! (over 33554432 bytes)
   at StableSwarmUI.Utils.Utilities.ReceiveData(WebSocket socket, Int32 maxBytes, CancellationToken limit) in C:\Code\StableSwarmUIAndrew\src\Utils\Utilities.cs:line 142
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, CancellationToken interrupt) in C:\Code\StableSwarmUIAndrew\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 277
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in C:\Code\StableSwarmUIAndrew\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 529
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in C:\Code\StableSwarmUIAndrew\src\Text2Image\T2IEngine.cs:line 275

**Comment by mcmonkey4eva** [comment]
Huh, you're upscaling... pretty big if you're getting 33MiB on a single image. I bumped the limit up to 100MiB. Hopefully should suffice now? Heh.
