### ISSUE TITLE
issues with docker version and nvidia

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#153]
I have a ubuntu20 I want to try the containerized version on.

I have successfully run OTHER nvidia accelerated containers on this box.

And when I run nvidia-smi inside the container, it correctly detects my gpu as:

  0  Quadro P620      
  
 Also, 
python3 torch.cuda.device_count()
returns 1

BUT.

The ComfyUI instance it tries to start, fails.

````
ComfyUI error: Traceback (most recent call last):
ComfyUI error:   File "/dlbackend/ComfyUI/main.py", line 72, in <module>
 ....
ComfyUI error:     return torch.device(torch.cuda.current_device())
ComfyUI error:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ComfyUI error:   File "/dlbackend/ComfyUI/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 769, in current_device
ComfyUI error:     _lazy_init()
ComfyUI error:   File "/dlbackend/ComfyUI/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
ComfyUI error:     torch._C._cuda_init()
ComfyUI error: RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

````

help please

**Comment by ppbrown** [comment]
apologies: problem was hardware on my end.
after laptop went to sleep, it disabled cuda access.
power cycle fixed the issue, docker containers run fine now
