### ISSUE TITLE
Error on Mac Studio : AttributeError: module 'torch' has no attribute 'mps'  Exception in thread Thread-1 (prompt_worker):

### ISSUE THREAD

**Issue by vicento** [Stability-AI/StableSwarmUI#18]
The UI start but show : Backends are still loading on the server...
i can select a model and type a prompt.

When i clic on Generate button i get this error : on terminal window
**_Thanks for any help..._**
```
Exception in thread Thread-1 (prompt_worker):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/Stef-T7-2/StefAI/StableSwarmUI/dlbackend/ComfyUI/main.py", line 88, in prompt_worker
    comfy.model_management.soft_empty_cache()
  File "/Volumes/Stef-T7-2/StefAI/StableSwarmUI/dlbackend/ComfyUI/comfy/model_management.py", line 549, in soft_empty_cache
    torch.mps.empty_cache()
AttributeError: module 'torch' has no attribute 'mps'
```

**Comment by mcmonkey4eva** [comment]
- Check: https://github.com/Stability-AI/StableSwarmUI/pull/14/files
- And here: https://github.com/comfyanonymous/ComfyUI#apple-mac-silicon
- per the comfy page, it might be helpful in SwarmUI to edit the Comfy backend (Server tab -> Backends) and edit the `Extra Args` input to have `--force-fp16`
