### ISSUE TITLE
new install fail, on ubuntu23

### ISSUE THREAD

**Issue by ppbrown** [Stability-AI/StableSwarmUI#198]
I just set up a new box with ubuntu23.
I installed dotnet7.
Did my usual github clone

did launch-linux.sh

it asked me the install and download questions, yadda yadda yadda.

what it DIDNT DO, is install the python deps.

> 21:53:15.071 [Info] Self-Start ComfyUI-0 on port 7821 had errors before shutdown:
ComfyUI-0 on port 7821 error: Traceback (most recent call last):
ComfyUI-0 on port 7821 error:   File "/home/phil/StableSwarmUI/dlbackend/ComfyUI/main.py", line 69, in <module>
ComfyUI-0 on port 7821 error:     import comfy.utils
ComfyUI-0 on port 7821 error:   File "/home/phil/StableSwarmUI/dlbackend/ComfyUI/comfy/utils.py", line 1, in <module>
ComfyUI-0 on port 7821 error:     import torch
ComfyUI-0 on port 7821 error: ModuleNotFoundError: No module named 'torch'

**Comment by ppbrown** [comment]
I guess this is technically not so much script failure, as "README needs updates" bug.

currently readme says (install python and git)

it doesnt explicitly say, "and pip and venv"

Theres also an additional pickiness with pip and ubuntu23.
By default, if you are NOT in a venv, it complains hard about using pip, with

"(use venv, or you have to say, --break-system-packages)"
