### ISSUE TITLE
Image prompts only work with SDXL base model?

### ISSUE THREAD

**Issue by Shadetail** [Stability-AI/StableSwarmUI#201]
I just updated to latest version from 2 days ago 0.5.9-Alpha (did a clean install just in case) and discovered the ability to drag and drop images onto prompt area in order to use them as image prompts, but this seems to only work with Stable Diffusion XL 1.0 Base model, and with any other model I tried I get an error:

```
10:50:55.687 [Error] Internal error processing T2I request: System.IO.InvalidDataException: Model type must be stable-diffusion-xl-v1-base for ReVision (currently is stable-diffusion-xl-v0_9-base). Set ReVision Strength to 0 if you just want IP-Adapter.
   at StableSwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.<>c.<.cctor>b__9_9(WorkflowGenerator g) in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 333
   at StableSwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.Generate() in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 952
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.CreateWorkflow(T2IParamInput user_input, Func`2 initImageFixer, String ModelFolderFormat, HashSet`1 features) in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 535
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput)
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 287
```

**Comment by mcmonkey4eva** [comment]
By default Image Prompt uses ReVision, which is indeed an XL-Specific feature.

You can also install https://github.com/laksjdjf/IPAdapter-ComfyUI to your comfy backend, at which point it will include an IP-Adapter option -- this has SDv1 support. (As I said in your other issue, I hope in the future to automate away common utilities like this so you don't have to manually install, but for now yeah)

You can also follow this issue: #176 regarding reference-only, which will likely be added into swarm in the near future and is also SDv1 compatible.

**Comment by Shadetail** [comment]
To clarify, I wasn't as surprised to see this not work with SDv1, as I was surprised to see it not work with any other SDXL models that I have, but only the official SDXL model. Since fine-tuned community SDXL models tend to be better quality than the base model, I tend to never really use the base model anymore, resulting in never being able to use this feature. But I see that the ComfyUI_IPAdapter_plus supports SDXL, so I assume adding this to my backend will enable the use of image prompts on community SDXL models as well.

Thank you for detailed explanation and the solution!

**Comment by mcmonkey4eva** [comment]
Oh, huh? That's odd. It should work on an SDXL model.
