### ISSUE TITLE
Is it expected that ControlNet doesn't work by default?

### ISSUE THREAD

**Issue by Shadetail** [Stability-AI/StableSwarmUI#202]
On a fresh install of latest Stable Swarm version 0.5.9-Alpha, I just enable it, drag and drop input image, select Canny, and select which ControlnetModel to use, like this:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/11357447/0302cb26-ed35-43b2-b01f-f1c69500b373)

And I get this error:
```
11:07:52.583 [Error] Internal error processing T2I request: System.NullReferenceException: Object reference not set to an instance of an object.
   at StableSwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.<>c__DisplayClass9_4.<.cctor>b__22(String _, JObject n) in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 489
   at StableSwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.CreateNode(String classType, Action`2 configure, String id) in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 914
   at StableSwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.<>c.<.cctor>b__9_11(WorkflowGenerator g) in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 476
   at StableSwarmUI.Builtin_ComfyUIBackend.WorkflowGenerator.Generate() in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\WorkflowGenerator.cs:line 949
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.CreateWorkflow(T2IParamInput user_input, Func`2 initImageFixer, String ModelFolderFormat, HashSet`1 features) in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 470
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput)
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in C:\Users\Mario\Documents\GitHub\StableSwarmUI2\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 287
```

Is some additional setup needed to get ControlNet to work? 

All I did in settings is browsed SDControlNetsFolder to the folder where I keep all my ControlNet models: C:\Users\Mario\Documents\GitHub\stable-diffusion-webui\models\ControlNet

**Comment by mcmonkey4eva** [comment]
That might've been a mistake on my part - if so, it's fixed now. If it wasn't, the other possible cause has an error check now that will give a clearer error message to identify what went wrong.
Just update (run `update-windows.bat`) and try again!

**Comment by Shadetail** [comment]
I updated and the error is gone, ControlNet works now! Thank you for such a quick fix!

Btw, I see that by default, only Canny preprocessor is available from the dropdown. Do you plan to add other ones there as well, or is this something that users are expected to populate themselves, presumably by installing comfyui manager and using it to install ComfyUI's ControlNet Auxiliary Preprocessors by Fannovel16?

**Comment by mcmonkey4eva** [comment]
`is this something that users are expected to populate themselves, presumably by installing comfyui manager and using it to install ComfyUI's ControlNet Auxiliary Preprocessors by Fannovel16?`
For now, yes, that ^

In the future though I do hope to automate away installation of common utilities, at most behind a `Do you want to install ControlNet Auxiliary Preprocessors by Fannovel16? Click [Here]` and then it does it for you, if not just fully preincluded without having to think about it.
