### ISSUE TITLE
Can't install rembg

### ISSUE THREAD

**Issue by mgsnell** [Stability-AI/StableSwarmUI#209]
I have a new install of StableSwarmUI 0.6.0.0 with comfyUI backend. I can install the comfyUI manager but cannot install the rembg module either through the manager or the manual way. However if I reinstall StableSwarmUI without the ComfyUI backend and then connect to my existing Comfy install then rembg works. I have attached a screen shot of StableSarmUI cmd line output.
Regards MGsnell

![cmd](https://github.com/Stability-AI/StableSwarmUI/assets/49707336/e6e6ef35-7fa7-4a0a-98b5-ca62137e1bb1)

**Comment by mgsnell** [comment]
Also I have attached a screen shot of a error I received after using the comfyUI mananger "Update all"
mgsnell

![error after using confyUI manager Update all](https://github.com/Stability-AI/StableSwarmUI/assets/49707336/98a27459-b803-4c43-966a-b9cd60064090)

**Comment by mcmonkey4eva** [comment]
Ah, latest comfy unstable builds are experimenting with python 3.12, which isn't compatible with everything yet. I've swapped to the stable link, so fresh installs from now on will use stable python and thus be able to load things like rembg fine.

**Comment by lostcowboy** [comment]
Hello, I am getting warnings like the above, what should I do? I am totally new to StableSwarmUi, totally new to Compfyui, and totally new to Stable-Diffusion. I did see a warning about dot net 0.8, I went to the URL and installed it and that warning has gone away. Yea! But what do I do about warnings like the above? The only thing I have added to the basic install is four Stable-Diffusion models and the Compfyui manager. I have run the install-windows.bat, and the update-windows.bat and the launch-windows.bat in that order. I did not see a change in the warning. Not sure where the right logs you would want are so I am doing a copy and past from server logs View:Debug.
2023-12-22 15:49:02.993 [Warning] ComfyUI-0 on port 7821 stdout: Traceback (most recent call last):
2023-12-22 15:49:02.994 [Warning] ComfyUI-0 on port 7821 stdout: File "H:\Swarm\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1813, in load_custom_node
2023-12-22 15:49:02.995 [Warning] ComfyUI-0 on port 7821 stdout: module_spec.loader.exec_module(module)
2023-12-22 15:49:02.996 [Warning] ComfyUI-0 on port 7821 stdout: File "", line 994, in exec_module
2023-12-22 15:49:02.997 [Warning] ComfyUI-0 on port 7821 stdout: File "", line 488, in _call_with_frames_removed
2023-12-22 15:49:02.998 [Warning] ComfyUI-0 on port 7821 stdout: File "H:\Swarm\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyExtra\__init__.py", line 1, in
2023-12-22 15:49:02.999 [Warning] ComfyUI-0 on port 7821 stdout: from . import SwarmRemBg, SwarmSaveAnimationWS
2023-12-22 15:49:03.000 [Warning] ComfyUI-0 on port 7821 stdout: File "H:\Swarm\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyExtra\SwarmRemBg.py", line 4, in
2023-12-22 15:49:03.001 [Warning] ComfyUI-0 on port 7821 stdout: from rembg import remove
2023-12-22 15:49:03.001 [Warning] ComfyUI-0 on port 7821 stdout: ModuleNotFoundError: No module named 'rembg'
2023-12-22 15:48:57.096 [Init] === StableSwarmUI v0.6.0.0 Starting ===
2023-12-22 15:48:57.137 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
2023-12-22 15:48:57.145 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
2023-12-22 15:48:57.146 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2023-12-22 15:48:57.147 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2023-12-22 15:48:57.148 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2023-12-22 15:48:57.149 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2023-12-22 15:48:57.152 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2023-12-22 15:48:57.177 [Init] Parsing command line...
2023-12-22 15:48:57.178 [Init] Loading settings file...
2023-12-22 15:48:57.188 [Init] Re-saving settings file...
2023-12-22 15:48:57.200 [Init] Applying command line settings...
2023-12-22 15:48:57.210 [Debug] [Load Time] Initial settings load took 0.11s (0.11s from start)
2023-12-22 15:48:57.217 [Debug] [Load Time] Extension PreInit took 0s (0.11s from start)
2023-12-22 15:48:57.217 [Init] Prepping options...
2023-12-22 15:48:57.283 [Debug] [Load Time] Prep Objects took 0.08s (0.19s from start)
2023-12-22 15:48:57.283 [Debug] [Load Time] Web PreInit took 0s (0.19s from start)
2023-12-22 15:48:57.289 [Debug] [Load Time] Extensions Init took 0s (0.19s from start)
2023-12-22 15:48:57.289 [Init] Loading models list...
2023-12-22 15:48:57.340 [Debug] [Load Time] Model listing took 0.05s (0.23s from start)
2023-12-22 15:48:57.340 [Init] Loading backends...
2023-12-22 15:48:57.341 [Init] Loading backends from file...
2023-12-22 15:48:57.348 [Debug] [Load Time] Backends took 0.02s (0.25s from start)
2023-12-22 15:48:57.348 [Init] Prepping API...
2023-12-22 15:48:57.349 [Init] Initializing backend #0 - ComfyUI Self-Starting...
2023-12-22 15:48:57.350 [Init] Backend request handler loop ready...
2023-12-22 15:48:57.351 [Debug] [Load Time] API took 0s (0.25s from start)
2023-12-22 15:48:57.351 [Init] Prepping webserver...
2023-12-22 15:48:57.384 [Debug] [Load Time] [Web] WebApp builder prep took 0.03s (0.03s from start)
2023-12-22 15:48:57.421 [Debug] [Load Time] [Web] WebApp build took 0.03s (0.06s from start)
2023-12-22 15:48:57.421 [Debug] [Load Time] [Web] exception handler took 0s (0.06s from start)
2023-12-22 15:48:57.421 [Debug] [Load Time] [Web] StartStop handler took 0s (0.06s from start)
2023-12-22 15:48:57.422 [Debug] [Load Time] [Web] static files took 0s (0.06s from start)
2023-12-22 15:48:57.466 [Debug] [Load Time] [Web] core use calls took 0.05s (0.11s from start)
2023-12-22 15:48:57.469 [Debug] [Load Time] [Web] core maps took 0s (0.11s from start)
2023-12-22 15:48:57.469 [Init] Scan for web extensions...
2023-12-22 15:48:57.472 [Debug] [Load Time] [Web] end took 0.02s (0.13s from start)
2023-12-22 15:48:57.472 [Debug] [Load Time] Web prep took 0.13s (0.38s from start)
2023-12-22 15:48:57.472 [Init] Readying extensions for launch...
2023-12-22 15:48:57.473 [Debug] [Load Time] Extensions pre-launch took 0s (0.38s from start)
2023-12-22 15:48:57.473 [Init] Launching server...
2023-12-22 15:48:57.474 [Init] Starting webserver on http://localhost:7801
2023-12-22 15:48:57.498 [Debug] [Load Time] Web launch took 0.02s (0.39s from start)
2023-12-22 15:48:57.498 [Init] Program is running.
2023-12-22 15:48:58.011 [Init] Launch web browser...
2023-12-22 15:48:58.477 [Info] Creating new admin session for 127.0.0.1
2023-12-22 15:48:58.518 [Debug] ComfyUI (Git Pull) stdout: Already up to date.
2023-12-22 15:48:58.521 [Info] Self-Start ComfyUI (Git Pull) exited properly.
2023-12-22 15:48:58.523 [Debug] Status of ComfyUI (Git Pull) after process end is RUNNING
2023-12-22 15:48:58.524 [Debug] (ComfyUI launch) Adding path H:\Swarm\StableSwarmUI\dlbackend\comfy\python_embeded
2023-12-22 15:48:59.349 [Debug] ComfyUI (Install rembg) stderr: ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11; 2.0.31 Requires-Python >3.7, <3.11; 2.0.32 Requires-Python >3.7, <3.11; 2.0.33 Requires-Python >3.7, <3.11; 2.0.34 Requires-Python >3.7, <3.11; 2.0.35 Requires-Python >3.7, <3.11; 2.0.36 Requires-Python >3.7, <3.11; 2.0.37 Requires-Python >3.7, <3.11; 2.0.38 Requires-Python >3.7, <3.11; 2.0.39 Requires-Python >3.7, <3.11; 2.0.40 Requires-Python >3.7, <3.11; 2.0.41 Requires-Python >=3.8, <3.12; 2.0.43 Requires-Python >=3.8, <3.12; 2.0.44 Requires-Python >=3.8, <3.12; 2.0.45 Requires-Python >=3.8, <3.12; 2.0.46 Requires-Python >=3.8, <3.12; 2.0.47 Requires-Python >=3.8, <3.12; 2.0.48 Requires-Python >=3.8, <3.12; 2.0.49 Requires-Python >=3.8, <3.12; 2.0.50 Requires-Python >=3.8, <3.12; 2.0.51 Requires-Python >=3.8, <3.12; 2.0.52 Requires-Python >=3.8, <3.12; 2.0.53 Requires-Python >=3.8, <3.12
2023-12-22 15:48:59.350 [Debug] ComfyUI (Install rembg) stderr: ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)
2023-12-22 15:48:59.350 [Debug] ComfyUI (Install rembg) stderr: ERROR: No matching distribution found for rembg
2023-12-22 15:48:59.394 [Debug] ComfyUI (Install rembg) stderr:
2023-12-22 15:48:59.394 [Debug] ComfyUI (Install rembg) stderr: [notice] A new release of pip is available: 23.3.1 -> 23.3.2
2023-12-22 15:48:59.394 [Debug] ComfyUI (Install rembg) stderr: [notice] To update, run: python.exe -m pip install --upgrade pip
2023-12-22 15:48:59.433 [Info] Self-Start ComfyUI (Install rembg) exited properly.
2023-12-22 15:48:59.435 [Debug] Status of ComfyUI (Install rembg) after process end is RUNNING
2023-12-22 15:48:59.438 [Debug] Requested generic launch of dlbackend/comfy/ComfyUI/main.py on GPU 0 from ComfyUI-0
2023-12-22 15:48:59.441 [Debug] (ComfyUI-0 launch) Adding path H:\Swarm\StableSwarmUI\dlbackend\comfy\python_embeded
2023-12-22 15:48:59.441 [Debug] (ComfyUI-0 launch) Will use python: H:\Swarm\StableSwarmUI\dlbackend\comfy\python_embeded\python.exe
2023-12-22 15:48:59.444 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
2023-12-22 15:48:59.485 [Debug] ComfyUI-0 on port 7821 stdout: ** ComfyUI startup time: 2023-12-22 15:48:59.484688
2023-12-22 15:48:59.518 [Debug] ComfyUI-0 on port 7821 stdout: ** Platform: Windows
2023-12-22 15:48:59.518 [Debug] ComfyUI-0 on port 7821 stdout: ** Python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec 7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
2023-12-22 15:48:59.518 [Debug] ComfyUI-0 on port 7821 stdout: ** Python executable: H:\Swarm\StableSwarmUI\dlbackend\comfy\python_embeded\python.exe
2023-12-22 15:48:59.518 [Debug] ComfyUI-0 on port 7821 stdout: ** Log path: H:\Swarm\StableSwarmUI\dlbackend\comfy\comfyui.log
2023-12-22 15:48:59.525 [Debug] ComfyUI-0 on port 7821 stdout:
2023-12-22 15:48:59.525 [Debug] ComfyUI-0 on port 7821 stdout: Prestartup times for custom nodes:
2023-12-22 15:48:59.525 [Debug] ComfyUI-0 on port 7821 stdout: 0.1 seconds: H:\Swarm\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2023-12-22 15:48:59.525 [Debug] ComfyUI-0 on port 7821 stdout:
2023-12-22 15:49:00.911 [Debug] ComfyUI-0 on port 7821 stdout: Total VRAM 11264 MB, total RAM 32693 MB
2023-12-22 15:49:00.911 [Debug] ComfyUI-0 on port 7821 stdout: Set vram state to: NORMAL_VRAM
2023-12-22 15:49:00.911 [Debug] ComfyUI-0 on port 7821 stdout: Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
2023-12-22 15:49:00.911 [Debug] ComfyUI-0 on port 7821 stdout: VAE dtype: torch.float32
2023-12-22 15:49:00.927 [Debug] ComfyUI-0 on port 7821 stdout: Using pytorch cross attention
2023-12-22 15:49:01.094 [Debug] ComfyUI-0 on port 7821 stderr: H:\Swarm\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
2023-12-22 15:49:01.095 [Debug] ComfyUI-0 on port 7821 stderr: _torch_pytree._register_pytree_node(
2023-12-22 15:49:01.520 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path checkpoints H:\Swarm\StableSwarmUI\Models\Stable-Diffusion
2023-12-22 15:49:01.520 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path vae H:\Swarm\StableSwarmUI\Models\VAE
2023-12-22 15:49:01.520 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path vae H:\Swarm\StableSwarmUI\Models\VAE
2023-12-22 15:49:01.520 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path loras H:\Swarm\StableSwarmUI\Models\Lora
2023-12-22 15:49:01.520 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path loras H:\Swarm\StableSwarmUI\Models\Lora
2023-12-22 15:49:01.520 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path loras H:\Swarm\StableSwarmUI\Models\LyCORIS
2023-12-22 15:49:01.520 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path upscale_models H:\Swarm\StableSwarmUI\Models\ESRGAN
2023-12-22 15:49:01.520 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path upscale_models H:\Swarm\StableSwarmUI\Models\RealESRGAN
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path upscale_models H:\Swarm\StableSwarmUI\Models\SwinIR
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path upscale_models H:\Swarm\StableSwarmUI\Models\upscale-models
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path upscale_models H:\Swarm\StableSwarmUI\Models\upscale_models
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path embeddings H:\Swarm\StableSwarmUI\Models\Embeddings
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path embeddings H:\Swarm\StableSwarmUI\Models\embeddings
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path hypernetworks H:\Swarm\StableSwarmUI\Models\hypernetworks
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path controlnet H:\Swarm\StableSwarmUI\Models\controlnet
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path controlnet H:\Swarm\StableSwarmUI\Models\ControlNet
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path clip_vision H:\Swarm\StableSwarmUI\Models\clip_vision
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path clip_vision H:\Swarm\StableSwarmUI\Models\clip_vision
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path custom_nodes H:\Swarm\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes
2023-12-22 15:49:01.521 [Debug] ComfyUI-0 on port 7821 stdout: Adding extra search path custom_nodes H:\Swarm\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes
2023-12-22 15:49:02.480 [Debug] ComfyUI-0 on port 7821 stdout: ### Loading: ComfyUI-Manager (V1.14)
2023-12-22 15:49:02.641 [Debug] ComfyUI-0 on port 7821 stdout: ### ComfyUI Revision: 1850 [36a79531] | Released on '2023-12-22'
2023-12-22 15:49:02.759 [Debug] ComfyUI-0 on port 7821 stdout: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2023-12-22 15:49:02.761 [Debug] ComfyUI-0 on port 7821 stdout: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2023-12-22 15:49:02.762 [Debug] ComfyUI-0 on port 7821 stdout: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2023-12-22 15:49:02.762 [Debug] ComfyUI-0 on port 7821 stdout: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2023-12-22 15:49:02.771 [Debug] ComfyUI-0 on port 7821 stderr: H:\Swarm\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
2023-12-22 15:49:02.771 [Debug] ComfyUI-0 on port 7821 stderr: _torch_pytree._register_pytree_node(
2023-12-22 15:49:02.827 [Debug] ComfyUI-0 on port 7821 stdout: [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2023-12-22 15:49:02.835 [Debug] ComfyUI-0 on port 7821 stdout: [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2023-12-22 15:49:02.838 [Debug] ComfyUI-0 on port 7821 stdout: [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2023-12-22 15:49:02.868 [Debug] ComfyUI-0 on port 7821 stdout: [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2023-12-22 15:49:02.977 [Debug] ComfyUI-0 on port 7821 stderr: H:\Swarm\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
2023-12-22 15:49:02.977 [Debug] ComfyUI-0 on port 7821 stderr: _torch_pytree._register_pytree_node(
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout:
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout: Cannot import H:\Swarm\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyExtra module for custom nodes: No module named 'rembg'
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout:
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout: Import times for custom nodes:
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout: 0.0 seconds (IMPORT FAILED): H:\Swarm\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyExtra
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout: 0.0 seconds: H:\Swarm\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\sd-dynamic-thresholding
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout: 0.2 seconds: H:\Swarm\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout: 0.3 seconds: H:\Swarm\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout:
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout: Starting server
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout:
2023-12-22 15:49:03.002 [Debug] ComfyUI-0 on port 7821 stdout: To see the GUI go to: http://127.0.0.1:7821
2023-12-22 15:49:03.036 [Debug] Comfy backend 0 using model folder format: backslash \ due to model OfficialStableDiffusion\sd_xl_base_1.0.safetensors
2023-12-22 15:49:03.038 [Init] Self-Start ComfyUI-0 on port 7821 started.
2023-12-22 15:49:03.039 [Debug] ComfyUI-0 self-start port 7821 loop ending (should now be alive)
2023-12-22 15:49:06.500 [Debug] Comfy backend 0 using model folder format: backslash \ due to model OfficialStableDiffusion\sd_xl_base_1.0.safetensors
2023-12-22 15:49:06.503 [Debug] Data refreshed!
2023-12-22 15:50:35.540 [Debug] ComfyUI-0 on port 7821 stdout: FETCH DATA from: H:\Swarm\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
2023-12-22 15:50:35.553 [Debug] Comfy backend direct websocket request to ws, have 1 backends available
2023-12-22 15:50:35.558 [Debug] Comfy backend direct offset for new user is 0
2023-12-22 15:51:31.304 [Debug] ComfyUI-0 on port 7821 stdout: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2023-12-22 15:51:31.409 [Debug] ComfyUI-0 on port 7821 stdout: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2023-12-22 15:51:31.482 [Debug] ComfyUI-0 on port 7821 stdout: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2023-12-22 15:51:31.561 [Debug] ComfyUI redirection gave non-200 code: '404' for URL: GET 'component/get_unresolved'

Sorry about that, I am sure there was a better way to get the information to you.
I will try moving the models folder(20GB) and deleting StableSwarmUI folder, and running install-windows.bat again then moving the models folder back.
