### ISSUE TITLE
Server got itself in trouble - 

### ISSUE THREAD

**Issue by Delicious-Bacon** [Stability-AI/StableSwarmUI#255]
First it worked, then I changed the Steps config from 20 to 2, generated an image, changed Steps to 40, generated an image, and after that, it no longer works. I restarted the server and ComfyUI. I restarted the PC. Nothing works.

Whatever I try to generate under any config, it gives me error code 500.

Log:
```
Info] User local requested 1 image with model 'dreamshaperXL_lightningDPMSDE.safetensors'...
21:05:53.519 [Error] Internal error processing T2I request: System.InvalidOperationException: Server turned 500 Internal Server Error, something went wrong: 500 Internal Server Error

Server got itself in trouble
   at StableSwarmUI.Backends.NetworkBackendUtils.Parse[JType](HttpResponseMessage message) in /home/usr/Programs/StableSwarmUI/src/Backends/NetworkBackendUtils.cs:line 35
   at StableSwarmUI.Utils.Utilities.PostJSONString(HttpClient client, String route, String input, CancellationToken interrupt) in /home/usr/Programs/StableSwarmUI/src/Utils/Utilities.cs:line 256
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in /home/usr/Programs/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 216
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in /home/usr/Programs/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 690
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in /home/usr/Programs/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 250
```

ComfyUI log:
```
Error handling request
Traceback (most recent call last):
  File "/home/usr/miniforge3/envs/diffusion/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/miniforge3/envs/diffusion/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/miniforge3/envs/diffusion/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/Programs/ComfyUI/server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/Programs/ComfyUI/server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/Programs/ComfyUI/execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'SwarmRemBg'
```

and another,

```
Error handling request
Traceback (most recent call last):
  File "/home/usr/miniforge3/envs/diffusion/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/miniforge3/envs/diffusion/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/miniforge3/envs/diffusion/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/Programs/ComfyUI/server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/Programs/ComfyUI/server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/Programs/ComfyUI/execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'SwarmModelTiling'

```

---

ComfyUI alone works without issues.

**Comment by mcmonkey4eva** [comment]
This looks like you're not using the `ComfyUI Self-Starting` backend, but rather using the ComfyUI-API-By-URL backend -- I don't recommend the API-by-URL option unless you absolutely know what you're doing with it (which, yknow, if you have to post an issue here, you don't).
Self-Start configures everything correctly for you.

**Comment by mcmonkey4eva** [comment]
`Yes, and adds another instance of ComfyUI, which I already have configured and packed with models, nodes etc.`
Self-Start is a launcher, not an installer. You give it the path to your existing install.

Again I must emphasize if you don't know what you're doing _in terms of Swarm's internal linkings_ just use the intended/standard routes, at least for long enough to learn how it works.

There's a doc about ideal multi-machine split setup here https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Using%20More%20GPUs.md

`Since today it works again, I'm guessing it was related to a network issue because I had a router reset.` the errors look like you had enabled Swarm parameters that use Swarm's nodes but swarm's nodes weren't installed on the remote comfy instance (this is an example of something self-start ensures for you).
