### ISSUE TITLE
Generation issue with Ec2 linux: Image generation fails

### ISSUE THREAD

**Issue by ashish-aesthisia** [Stability-AI/StableSwarmUI#277]
**Cloud Provider:** AWS EC2
**Cuda Version:** 12.0 
**Graphics Card:** Tesla , 16GB Vram

**OS:** Ubuntu 22.04

**Launch command:** `./launch-linux.sh --host 0.0.0.0 --port 7860 --launch_mode none`

**Proxy:** None
**Access:** Over public IP
<img width="1439" alt="Screenshot 2024-03-24 at 12 10 47 PM" src="https://github.com/Stability-AI/StableSwarmUI/assets/108272701/a7ace1bb-e87a-4d63-b2cb-e1087b42d880">

**Console Logs**

```
06:32:17.831 [Init] === StableSwarmUI v0.6.2.0 Starting ===
06:32:17.881 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
06:32:17.893 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
06:32:17.893 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
06:32:17.894 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
06:32:17.894 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
06:32:17.894 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
06:32:17.895 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
06:32:17.922 [Init] Parsing command line...
06:32:17.935 [Init] Loading settings file...
06:32:17.966 [Init] Re-saving settings file...
06:32:17.985 [Init] Applying command line settings...
06:32:17.990 [Warning] Port 7860 looks like a port commonly used by other programs. You may want to change it.
06:32:18.008 [Init] Prepping options...
06:32:18.166 [Init] Loading models list...
06:32:18.216 [Init] Loading backends...
06:32:18.217 [Init] Loading backends from file...
06:32:18.226 [Init] Prepping API...
06:32:18.227 [Init] Initializing backend #0 - ComfyUI Self-Starting...
06:32:18.228 [Init] Backend request handler loop ready...
06:32:18.230 [Init] Prepping webserver...
06:32:18.316 [Info] Self-Start ComfyUI (Git Pull) exited properly.
Already up to date.
06:32:18.344 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
06:32:18.423 [Init] Scan for web extensions...
06:32:18.424 [Init] Readying extensions for launch...
06:32:18.424 [Init] Launching server...
06:32:18.424 [Init] Starting webserver on http://0.0.0.0:7860
06:32:18.475 [Init] Program is running.
06:32:22.423 [Init] Self-Start ComfyUI-0 on port 7821 started.
06:34:58.902 [Info] Creating new admin session 'local' for 122.180.145.135
06:36:17.459 [Info] ComfyUI backend 0 shutting down...
06:36:17.459 [Info] Shutting down self-start ComfyUI (port=7821) process #3465...
06:36:17.530 [Info] Self-Start ComfyUI-0 on port 7821 exited properly from disabling.
06:36:18.470 [Init] Initializing backend #0 - ComfyUI Self-Starting...
06:36:18.487 [Info] Saving backends...
Already up to date.
06:36:18.556 [Info] Self-Start ComfyUI (Git Pull) exited properly.
06:36:18.559 [Init] Self-Start ComfyUI-0 on port 7822 is loading...
06:36:22.575 [Init] Self-Start ComfyUI-0 on port 7822 started.
06:36:44.557 [Info] User local requested 1 image with model 'OfficialStableDiffusion/sd_xl_base_1.0.safetensors'...
06:37:06.121 [Warning] ComfyUI-0 on port 7822 stderr: Traceback (most recent call last):
06:37:06.122 [Warning] ComfyUI-0 on port 7822 stderr: RuntimeError: CUDA error: an illegal memory access was encountered
06:37:06.568 [Error] Internal error processing T2I request: System.Net.Http.HttpRequestException: Connection refused (localhost:7822)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.SendGet[JType](String url, CancellationToken token) in /home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 714
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in /home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 368
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in /home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 690
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in /home/ubuntu/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 250
06:37:06.597 [Info] Self-Start ComfyUI-0 on port 7822 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
06:37:06.597 [Info] Self-Start ComfyUI-0 on port 7822 had errors before shutdown:
ComfyUI-0 on port 7822 error: Total VRAM 14960 MB, total RAM 15706 MB
ComfyUI-0 on port 7822 error: Set vram state to: NORMAL_VRAM
ComfyUI-0 on port 7822 error: Device: cuda:0 Tesla T4 : cudaMallocAsync
ComfyUI-0 on port 7822 error: VAE dtype: torch.float32
ComfyUI-0 on port 7822 error: Using pytorch cross attention
ComfyUI-0 on port 7822 error: Adding extra search path checkpoints /home/ubuntu/StableSwarmUI/Models/Stable-Diffusion
ComfyUI-0 on port 7822 error: Adding extra search path vae /home/ubuntu/StableSwarmUI/Models/VAE
ComfyUI-0 on port 7822 error: Adding extra search path vae /home/ubuntu/StableSwarmUI/Models/VAE
ComfyUI-0 on port 7822 error: Adding extra search path loras /home/ubuntu/StableSwarmUI/Models/Lora
ComfyUI-0 on port 7822 error: Adding extra search path loras /home/ubuntu/StableSwarmUI/Models/Lora
ComfyUI-0 on port 7822 error: Adding extra search path loras /home/ubuntu/StableSwarmUI/Models/LyCORIS
ComfyUI-0 on port 7822 error: Adding extra search path upscale_models /home/ubuntu/StableSwarmUI/Models/ESRGAN
ComfyUI-0 on port 7822 error: Adding extra search path upscale_models /home/ubuntu/StableSwarmUI/Models/RealESRGAN
ComfyUI-0 on port 7822 error: Adding extra search path upscale_models /home/ubuntu/StableSwarmUI/Models/SwinIR
ComfyUI-0 on port 7822 error: Adding extra search path upscale_models /home/ubuntu/StableSwarmUI/Models/upscale-models
ComfyUI-0 on port 7822 error: Adding extra search path upscale_models /home/ubuntu/StableSwarmUI/Models/upscale_models
ComfyUI-0 on port 7822 error: Adding extra search path embeddings /home/ubuntu/StableSwarmUI/Models/Embeddings
ComfyUI-0 on port 7822 error: Adding extra search path embeddings /home/ubuntu/StableSwarmUI/Models/embeddings
ComfyUI-0 on port 7822 error: Adding extra search path hypernetworks /home/ubuntu/StableSwarmUI/Models/hypernetworks
ComfyUI-0 on port 7822 error: Adding extra search path controlnet /home/ubuntu/StableSwarmUI/Models/controlnet
ComfyUI-0 on port 7822 error: Adding extra search path controlnet /home/ubuntu/StableSwarmUI/Models/ControlNet
ComfyUI-0 on port 7822 error: Adding extra search path clip_vision /home/ubuntu/StableSwarmUI/Models/clip_vision
ComfyUI-0 on port 7822 error: Adding extra search path clip_vision /home/ubuntu/StableSwarmUI/Models/clip_vision
ComfyUI-0 on port 7822 error: Adding extra search path clip /home/ubuntu/StableSwarmUI/Models/clip
ComfyUI-0 on port 7822 error: Adding extra search path unet /home/ubuntu/StableSwarmUI/Models/unet
ComfyUI-0 on port 7822 error: Adding extra search path gligen /home/ubuntu/StableSwarmUI/Models/gligen
ComfyUI-0 on port 7822 error: Adding extra search path custom_nodes /home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes
ComfyUI-0 on port 7822 error: Adding extra search path custom_nodes /home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes
ComfyUI-0 on port 7822 error: 
ComfyUI-0 on port 7822 error: Import times for custom nodes:
ComfyUI-0 on port 7822 error:    0.0 seconds: /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/websocket_image_save.py
ComfyUI-0 on port 7822 error:    0.0 seconds: /home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/DLNodes/sd-dynamic-thresholding
ComfyUI-0 on port 7822 error:    0.1 seconds: /home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyCommon
ComfyUI-0 on port 7822 error:    0.7 seconds: /home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra
ComfyUI-0 on port 7822 error: 
ComfyUI-0 on port 7822 error: Starting server
ComfyUI-0 on port 7822 error: 
ComfyUI-0 on port 7822 error: To see the GUI go to: http://127.0.0.1:7822
ComfyUI-0 on port 7822 error: got prompt
ComfyUI-0 on port 7822 error: model_type EPS
ComfyUI-0 on port 7822 error: Using pytorch attention in VAE
ComfyUI-0 on port 7822 error: Using pytorch attention in VAE
ComfyUI-0 on port 7822 error: clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
ComfyUI-0 on port 7822 error: loaded straight to GPU
ComfyUI-0 on port 7822 error: Requested to load SDXL
ComfyUI-0 on port 7822 error: Loading 1 new model
ComfyUI-0 on port 7822 error: Requested to load AutoencoderKL
ComfyUI-0 on port 7822 error: Loading 1 new model
ComfyUI-0 on port 7822 error: Prompt executed in 3.96 seconds
ComfyUI-0 on port 7822 error: got prompt
ComfyUI-0 on port 7822 error: Requested to load SDXLClipModel
ComfyUI-0 on port 7822 error: Loading 1 new model
ComfyUI-0 on port 7822 error: 
ComfyUI-0 on port 7822 error:   0%|          | 0/20 [00:00<?, ?it/s]
ComfyUI-0 on port 7822 error:   5%|▌         | 1/20 [00:01<00:35,  1.86s/it]
ComfyUI-0 on port 7822 error:  10%|█         | 2/20 [00:03<00:32,  1.82s/it]
ComfyUI-0 on port 7822 error:  15%|█▌        | 3/20 [00:05<00:30,  1.80s/it]
ComfyUI-0 on port 7822 error:  20%|██        | 4/20 [00:07<00:28,  1.80s/it]
ComfyUI-0 on port 7822 error:  25%|██▌       | 5/20 [00:09<00:26,  1.79s/it]
ComfyUI-0 on port 7822 error:  30%|███       | 6/20 [00:10<00:25,  1.79s/it]
ComfyUI-0 on port 7822 error:  35%|███▌      | 7/20 [00:12<00:23,  1.79s/it]
ComfyUI-0 on port 7822 error:  40%|████      | 8/20 [00:14<00:21,  1.79s/it]
ComfyUI-0 on port 7822 error:  40%|████      | 8/20 [00:15<00:23,  1.93s/it]
ComfyUI-0 on port 7822 error: !!! Exception during processing !!!
ComfyUI-0 on port 7822 error: Traceback (most recent call last):
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 151, in recursive_execute
ComfyUI-0 on port 7822 error:     output_data, output_ui = get_output_data(obj, input_data_all)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 81, in get_output_data
ComfyUI-0 on port 7822 error:     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 74, in map_node_over_list
ComfyUI-0 on port 7822 error:     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyCommon/SwarmKSampler.py", line 152, in sample
ComfyUI-0 on port 7822 error:     samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_samples,
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/comfy/sample.py", line 100, in sample
ComfyUI-0 on port 7822 error:     samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/comfy/samplers.py", line 705, in sample
ComfyUI-0 on port 7822 error:     return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/comfy/samplers.py", line 610, in sample
ComfyUI-0 on port 7822 error:     samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/comfy/samplers.py", line 548, in sample
ComfyUI-0 on port 7822 error:     samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ComfyUI-0 on port 7822 error:     return func(*args, **kwargs)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/comfy/k_diffusion/sampling.py", line 140, in sample_euler
ComfyUI-0 on port 7822 error:     callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigma_hat, 'denoised': denoised})
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/comfy/samplers.py", line 546, in <lambda>
ComfyUI-0 on port 7822 error:     k_callback = lambda x: callback(x["i"], x["denoised"], x["x"], total_steps)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyCommon/SwarmKSampler.py", line 84, in callback
ComfyUI-0 on port 7822 error:     preview_img = previewer.decode_latent_to_preview_image("JPEG", x0[i:i+1])
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/latent_preview.py", line 18, in decode_latent_to_preview_image
ComfyUI-0 on port 7822 error:     preview_image = self.decode_latent_to_preview(x0)
ComfyUI-0 on port 7822 error:   File "/home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/latent_preview.py", line 40, in decode_latent_to_preview
ComfyUI-0 on port 7822 error:     latent_image = x0[0].permute(1, 2, 0).cpu() @ self.latent_rgb_factors
ComfyUI-0 on port 7822 error: RuntimeError: CUDA error: an illegal memory access was encountered
ComfyUI-0 on port 7822 error: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ComfyUI-0 on port 7822 error: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ComfyUI-0 on port 7822 error: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ComfyUI-0 on port 7822 error: 
ComfyUI-0 on port 7822 error: 
ComfyUI-0 on port 7822 error: Prompt executed in 16.53 seconds
ComfyUI-0 on port 7822 error: terminate called after throwing an instance of 'c10::Error'
ComfyUI-0 on port 7822 error:   what():  CUDA error: an illegal memory access was encountered
ComfyUI-0 on port 7822 error: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ComfyUI-0 on port 7822 error: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ComfyUI-0 on port 7822 error: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ComfyUI-0 on port 7822 error: 
ComfyUI-0 on port 7822 error: Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
ComfyUI-0 on port 7822 error: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f82b3009d87 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
ComfyUI-0 on port 7822 error: frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f82b2fba75f in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
ComfyUI-0 on port 7822 error: frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f82b30da8a8 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
ComfyUI-0 on port 7822 error: frame #3: <unknown function> + 0x571d0 (0x7f82b30df1d0 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
ComfyUI-0 on port 7822 error: frame #4: <unknown function> + 0x58f14 (0x7f82b30e0f14 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
ComfyUI-0 on port 7822 error: frame #5: <unknown function> + 0x540210 (0x7f82fd0cc210 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
ComfyUI-0 on port 7822 error: frame #6: <unknown function> + 0x649bf (0x7f82b2fee9bf in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
ComfyUI-0 on port 7822 error: frame #7: c10::TensorImpl::~TensorImpl() + 0x21b (0x7f82b2fe7c8b in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
ComfyUI-0 on port 7822 error: frame #8: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f82b2fe7e39 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libc10.so)
ComfyUI-0 on port 7822 error: frame #9: <unknown function> + 0x802b98 (0x7f82fd38eb98 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
ComfyUI-0 on port 7822 error: frame #10: <unknown function> + 0x15642e (0x556c0c33342e in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #11: <unknown function> + 0x249c9e (0x556c0c426c9e in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #12: <unknown function> + 0x26d0dc (0x556c0c44a0dc in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #13: <unknown function> + 0x16a564 (0x556c0c347564 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #14: _PyEval_EvalFrameDefault + 0x5456 (0x556c0c3ed536 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #15: _PyFunction_Vectorcall + 0x25c (0x556c0c39229c in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #16: PyObject_Call + 0x86 (0x556c0c3445c6 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #17: _PyEval_EvalFrameDefault + 0x2e7a (0x556c0c3eaf5a in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #18: _PyFunction_Vectorcall + 0x25c (0x556c0c39229c in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #19: _PyEval_EvalFrameDefault + 0x76a (0x556c0c3e884a in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #20: _PyFunction_Vectorcall + 0x25c (0x556c0c39229c in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #21: _PyEval_EvalFrameDefault + 0x76a (0x556c0c3e884a in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #22: <unknown function> + 0x1b2f99 (0x556c0c38ff99 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #23: <unknown function> + 0x1b6ac5 (0x556c0c393ac5 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #24: PyObject_Call + 0x86 (0x556c0c3445c6 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #25: <unknown function> + 0x2a6c7a (0x556c0c483c7a in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #26: <unknown function> + 0x23d848 (0x556c0c41a848 in /home/ubuntu/StableSwarmUI/dlbackend/ComfyUI/venv/bin/python3)
ComfyUI-0 on port 7822 error: frame #27: <unknown function> + 0x8609 (0x7f82ff7e5609 in /lib/x86_64-linux-gnu/libpthread.so.0)
ComfyUI-0 on port 7822 error: frame #28: clone + 0x43 (0x7f82ff91f353 in /lib/x86_64-linux-gnu/libc.so.6)
ComfyUI-0 on port 7822 error:
```

**What i have tried so far:** 

1. Check machine firewall, ports are open. 
2. Checked cuda drivers, `nvidia-smi` works. 
3. Checked github issues for any reference. 
4. Reconfigured swarm to run on lan. 

**Questions:**

1. How to run comfy backend on 0.0.0.0 as currently it seems like listening on 127.0.0.1
2. Do you have enabled queue or gradio-queue by enabled by default? Do we have an option to run it on TCP/HTTPs mode only?

**Comment by mcmonkey4eva** [comment]
**The error**: Thaaat's a cuda error, ie the issue is somewhere in the range of hardware/drivers/pytorch/maaaybe comfy/not swarm. Sorry not much help I can offer on diagnosing that.

`How to run comfy backend on 0.0.0.0 as currently it seems like listening on 127.0.0.1`
the comfy instance is intentionally local.
You can swap swarm to `0.0.0.0` in the Server Configuration tab -> `Host` setting, or launch with `--host 0.0.0.0` on cli (see https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Command%20Line%20Arguments.md for docs on CLI)
You can access the comfy direct backend (eg for API usage?) by just opening contacting `http://localhost:7801/ComfyBackendDirect/` it will autoredirect to your first valid comfy backend.

`Do you have enabled queue or gradio-queue by enabled by default?` What? I don't know what this question means. Gradio is a project unrelated to anything here.
If you want an auto remote connection you can use cloudflared, see docs here https://github.com/Stability-AI/StableSwarmUI/blob/master/docs/Advanced%20Usage.md#accessing-stableswarmui-from-other-devices

`Do we have an option to run it on TCP/HTTPs mode only?` TCP is the only option yes. for HTTPS you would need to use a proxy layer (eg cloudflared for generated remote address, or apache2/nginx for internal reverse proxy).

**Comment by ashish-aesthisia** [comment]
> ./launch-linux.sh --host 0.0.0.0 --port 7860 --launch_mode none

I have updated few things: 
- Using default port. 
- Upgraded to bigger instance. 
- Reinstalled all dependencies e.g. cuda, pytorch, venv etc. 

It was definitely not an error with the comfy backend. 

Seems like it's working. Thanks
