### ISSUE TITLE
Is there a tab for downloading custom ControlNet or similar models?

### ISSUE THREAD

**Issue by IamTirion** [Stability-AI/StableSwarmUI#285]
There are so many different types of ControlNet, like IPAdapter or T2IAdapater, or things like PhotoMaker, and new ones coming out quite often. I find it very hard to keep track of all of them, or to know which ones are more modern. Is there a tab or a list for downloading them like the Extensions tab in Automatic1111? I think there is also something similar in ComfyUI but I'm not sure.

**Comment by mcmonkey4eva** [comment]
_Extensions_ and _Models_ are different.

Note also IPAdapter is not ControlNet, those are two different (but similar) things. There are plans in the future to make the interface for image-input-handlers more agnostic of what tool is handling them. Atm controlnets go in the "controlnet" parameter on the left, whereas ReVision or IPAdapter inputs you drag an image to the prompt box.

For models you'd probably want to browse https://civitai.com/ or HuggingFace.

For extensions, Swarm supports Comfy extension in the Comfy tab, so you can use https://github.com/ltdrdata/ComfyUI-Manager for that -- a few comfy extensions also have native support in swarm (eg ControlNet Preprocessors Aux, or Cubiq's IP Adapter).

Swarm-extensions are easy to build but thus far has not been done much, as most features get integrated directly to Swarm itself rather than left for external extension to implement.

**Comment by IamTirion** [comment]
Sorry for misusing the terms. I don't know the general term that ControlNet and IPAdapter both belong to.

I have another question that is related to my original question. If I use ComfyUI, and I want to use IPAdapter. The way I know to do that is to install the IPAdapter nodes through ComfyUI Manager, and then I have to connect the nodes in a specific way to use IPAdapter. I find it hard to make it work. If I want to install IPAdapter in Stable Swarm UI, do I go through the same process in the Comfy Workflow Editor, or do I install things differently in Stable Swarm UI?

**Comment by mcmonkey4eva** [comment]
if you install cubiq's ip adapter extension to the comfy backend (and restart swarm after), you can simply drag an image to the prompt box and select the ip adapter model in parameters at the top left

**Comment by IamTirion** [comment]
Well, I downloaded the ComfyUI Manager, and then I installed Cubiq's IP Adapter Extension, then installed ip-adapter_sdxl.safetensors through the Manager again. I see the IP Adapter option in the parameters, but it didn't work for me. I got this error message:

00:43:14.133 [Info] User local requested 1 image with model 'ProteusV0.3.safetensors'...
00:46:59.053 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
00:46:59.089 [Error] Internal error processing T2I request: System.InvalidOperationException: Server turned 500 Internal Server Error, something went wrong: 500 Internal Server Error

Server got itself in trouble
   at StableSwarmUI.Backends.NetworkBackendUtils.Parse[JType](HttpResponseMessage message) in D:\Stable Swarm UI\StableSwarmUI\src\Backends\NetworkBackendUtils.cs:line 35
   at StableSwarmUI.Utils.Utilities.PostJSONString(HttpClient client, String route, String input, CancellationToken interrupt) in D:\Stable Swarm UI\StableSwarmUI\src\Utils\Utilities.cs:line 256
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in D:\Stable Swarm UI\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 216
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in D:\Stable Swarm UI\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 690
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in D:\Stable Swarm UI\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 250

**Comment by mcmonkey4eva** [comment]
go to server -> logs -> set view type to 'debug', check debug logs

**Comment by IamTirion** [comment]
2024-04-03 00:46:59.088 [Debug] Failed to process comfy workflow: { "4": { "class_type": "CheckpointLoaderSimple", "inputs": { "ckpt_name": "ProteusV0.3.safetensors" } }, "5": { "class_type": "EmptyLatentImage", "inputs": { "batch_size": 1, "height": 768, "width": 1344 } }, "6": { "class_type": "CLIPTextEncodeSDXL", "inputs": { "clip": [ "4", 1 ], "text_g": "", "text_l": "", "crop_w": 0, "crop_h": 0, "width": 2048, "height": 1152, "target_width": 1344, "target_height": 768 } }, "100": { "class_type": "CLIPVisionLoader", "inputs": { "clip_name": "clip_vision_g.safetensors" } }, "101": { "class_type": "ConditioningZeroOut", "inputs": { "conditioning": [ "6", 0 ] } }, "102": { "class_type": "ConditioningZeroOut", "inputs": { "conditioning": [ "7", 0 ] } }, "103": { "class_type": "SwarmLoadImageB64", "inputs": { "image_base64": "iVBORw0KGgoAAAANSUhEUgAAB+AAAASACAIAAABAz8N8AAEAAElEQVR4nHT924IlSZIjiAGi5hFR1d2zs1z+FV/4wP//ht2dma6MOKYCPgCiZp5NRldnZrifYxdVEQjkqvz//L//X1UlbYgCSKilFgBBmD8SABEQAPqvAOhfEhRE+ndAzQdFQSDl7+dbguSfgPkk9Pw/SUkEc/l8hyQJkfQ3ivkjgH4UgsT5QRUoLZJQzdVIv6SqIEGUX0cSO..." } }, "104": { "class_type": "CLIPVisionEncode", "inputs": { "clip_vision": [ "100", 0 ], "image": [ "103", 0 ] } }, "105": { "class_type": "unCLIPConditioning", "inputs": { "conditioning": [ "101", 0 ], "clip_vision_output": [ "104", 0 ], "strength": 1, "noise_augmentation": 0 } }, "106": { "class_type": "SwarmLoadImageB64", "inputs": { "image_base64": "iVBORw0KGgoAAAANSUhEUgAAB+AAAASACAIAAABAz8N8AAEAAElEQVR4nHT924IlSZIjiAGi5hFR1d2zs1z+FV/4wP//ht2dma6MOKYCPgCiZp5NRldnZrifYxdVEQjkqvz//L//X1UlbYgCSKilFgBBmD8SABEQAPqvAOhfEhRE+ndAzQdFQSDl7+dbguSfgPkk9Pw/SUkEc/l8hyQJkfQ3ivkjgH4UgsT5QRUoLZJQzdVIv6SqIEGUX0cSO..." } }, "107": { "class_type": "IPAdapterModelLoader", "inputs": { "ipadapter_file": "ip-adapter_sdxl.safetensors" } }, "108": { "class_type": "IPAdapterApply", "inputs": { "ipadapter": [ "107", 0 ], "model": [ "4", 0 ], "image": [ "106", 0 ], "clip_vision": [ "100", 0 ], "weight": 1, "noise": 0, "weight_type": "original" } }, "7": { "class_type": "CLIPTextEncodeSDXL", "inputs": { "clip": [ "4", 1 ], "text_g": "", "text_l": "", "crop_w": 0, "crop_h": 0, "width": 1088, "height": 640, "target_width": 1344, "target_height": 768 } }, "10": { "class_type": "SwarmKSampler", "inputs": { "model": [ "108", 0 ], "noise_seed": 1351554495, "steps": 20, "cfg": 7, "sampler_name": "euler", "scheduler": "normal", "positive": [ "105", 0 ], "negative": [ "7", 0 ], "latent_image": [ "5", 0 ], "start_at_step": 0, "end_at_step": 10000, "return_with_leftover_noise": "disable", "add_noise": "enable", "var_seed": 0, "var_seed_strength": 0, "sigma_min": -1, "sigma_max": -1, "rho": 7, "previews": "default" } }, "8": { "class_type": "VAEDecode", "inputs": { "vae": [ "4", 2 ], "samples": [ "10", 0 ] } }, "9": { "class_type": "SwarmSaveImageWS", "inputs": { "images": [ "8", 0 ] } } } for inputs T2IParamInput(prompt: , revisionstrength: 1, useipadapter: ip-adapter_sdxl.safetensors, seed: 1351554495, steps: 20, cfgscale: 7, aspectratio: 16:9, width: 1344, height: 768, model: ProteusV0.3.safetensors, promptimages: iVBORw0KGgoAAAANSUhEUgAAB+AAAASACAIAAABAz8N8AAEAAElEQVR4nHT924IlSZIjiAGi5hFR1d2zs1z+FV/4wP//ht2dma6MOKYCPgCiZp5NRldnZrifYxdVEQjkqvz//L//X1UlbYgCSKilFgBBmD8SABEQAPqvAOhfEhRE+ndAzQdFQSDl7+dbguSfgPkk9Pw/SUkEc/l8hyQJkfQ3ivkjgH4UgsT5QRUoLZJQzdVIv6SqIEGUX0cSOM8g..., negativeprompt: )
2024-04-03 00:46:59.091 [Debug] Refused to generate image for local: Something went wrong while generating images.

**Comment by IamTirion** [comment]
Actually, the debug log is much longer than this. I don't know where I should start posting.

**Comment by Komorebi-yaodong** [comment]
> Well, I downloaded the ComfyUI Manager, and then I installed Cubiq's IP Adapter Extension, then installed ip-adapter_sdxl.safetensors through the Manager again. I see the IP Adapter option in the parameters, but it didn't work for me. I got this error message:
> 
> 00:43:14.133 [Info] User local requested 1 image with model 'ProteusV0.3.safetensors'... 00:46:59.053 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last): 00:46:59.089 [Error] Internal error processing T2I request: System.InvalidOperationException: Server turned 500 Internal Server Error, something went wrong: 500 Internal Server Error
> 
> Server got itself in trouble at StableSwarmUI.Backends.NetworkBackendUtils.Parse[JType](HttpResponseMessage message) in D:\Stable Swarm UI\StableSwarmUI\src\Backends\NetworkBackendUtils.cs:line 35 at StableSwarmUI.Utils.Utilities.PostJSONString(HttpClient client, String route, String input, CancellationToken interrupt) in D:\Stable Swarm UI\StableSwarmUI\src\Utils\Utilities.cs:line 256 at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in D:\Stable Swarm UI\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 216 at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in D:\Stable Swarm UI\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 690 at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in D:\Stable Swarm UI\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 250

I'm experiencing a similar issue to these reported errors, and above these reported errors there is a reference to KeyError: 'IPAdapterApply', which I believe is an error generated after a major update to the IPAdapter node, and StableSwarm hasn't updated these configurations yet, because IPAdapterApply is being removed from the new node. and nodes such as IPAdapterAdvanced are used

**Comment by mcmonkey4eva** [comment]
Hi, sorry the delay, the new version of cubiq's IP Adapter now works natively again - I also added automatic model downloading to match the new unified preset loader setup

**Comment by Komorebi-yaodong** [comment]
```
2024-04-23 08:55:24.015 [ComfyUI-1 on port 8188] stderr: got prompt
2024-04-23 08:55:24.018 [ComfyUI-1 on port 8188] stdout: [32m[rgthree] Using rgthree's optimized recursive execution.[0m
2024-04-23 08:55:24.588 [ComfyUI-1 on port 8188] stderr: model_type EPS
2024-04-23 08:55:34.361 [ComfyUI-1 on port 8188] stderr: Using pytorch attention in VAE
2024-04-23 08:55:34.364 [ComfyUI-1 on port 8188] stderr: Using pytorch attention in VAE
2024-04-23 08:55:37.861 [ComfyUI-1 on port 8188] stderr: clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
2024-04-23 08:55:37.861 [ComfyUI-1 on port 8188] stderr: loaded straight to GPU
2024-04-23 08:55:37.861 [ComfyUI-1 on port 8188] stderr: Requested to load SDXL
2024-04-23 08:55:37.861 [ComfyUI-1 on port 8188] stderr: Loading 1 new model
2024-04-23 08:55:37.861 [ComfyUI-1 on port 8188] stderr: loading in lowvram mode 64.0
2024-04-23 08:55:38.295 [ComfyUI-1 on port 8188] stderr: Requested to load AutoencoderKL
2024-04-23 08:55:38.295 [ComfyUI-1 on port 8188] stderr: Loading 1 new model
2024-04-23 08:55:42.872 [ComfyUI-1 on port 8188] stderr: Prompt executed in 18.85 seconds
2024-04-23 08:56:29.261 [ComfyUI-1 on port 8188] stderr: got prompt
2024-04-23 08:56:29.279 [ComfyUI-1 on port 8188] stderr: Failed to validate prompt for output 9:
2024-04-23 08:56:29.279 [ComfyUI-1 on port 8188] stderr: * IPAdapterUnifiedLoader 106:
2024-04-23 08:56:29.279 [ComfyUI-1 on port 8188] stderr:   - Value not in list: preset: 'ip-adapter-faceid-plusv2_sdxl.bin' not in ['LIGHT - SD1.5 only (low strength)', 'STANDARD (medium strength)', 'VIT-G (medium strength)', 'PLUS (high strength)', 'PLUS FACE (portraits)', 'FULL FACE - SD1.5 only (portraits stronger)']
```
Thank you for your contribution but I still got error.

**Comment by mcmonkey4eva** [comment]
Re the error: I fixed it to no longer show the non-unified model names

re `because sdxl-lightning models are shown as sdxl-base0.9.` this is an error of the relevant model's metadata (ie blame the model author for not following metadata spec). You can edit the model metadata yourself in Swarm, just click:
![image](https://github.com/Stability-AI/StableSwarmUI/assets/4000772/f7b73d19-c95d-4bac-b34a-b0ea8e0154f8)
and set `architecture` to `stable-diffusion-xl-v1-base`

**Comment by Komorebi-yaodong** [comment]
> Re the error: I fixed it to no longer show the non-unified model names

Thank you! After the update, it's effective. May I ask if the feature of faceid will be added?

**Comment by mcmonkey4eva** [comment]
I was hoping if I didn't add FaceID support just nobody would ask and all would be happy. But yeah since you've immediately asked, probably other people want it too, so...

the above commit is mildly cursed, as FaceID depends on insightface which is not compatible to install on most systems, but the ReActor developer has a custom wheel that works, which... I hate hardcoding that in but it oughtta cover the majority of average users better, so...

**Comment by Komorebi-yaodong** [comment]
> I was hoping if I didn't add FaceID support just nobody would ask and all would be happy. But yeah since you've immediately asked, probably other people want it too, so...
> 
> the above commit is mildly cursed, as FaceID depends on insightface which is not compatible to install on most systems, but the ReActor developer has a custom wheel that works, which... I hate hardcoding that in but it oughtta cover the majority of average users better, so...

With great respect and thanks for your contribution!
