### ISSUE TITLE
[BUG] Cannot load a model

### ISSUE THREAD

**Issue by bkosowski** [Stability-AI/StableSwarmUI#349]
Version installed today.
Path to models "D:\AI\SD\SDXL_Models" set in the settings. All my models are visible as cards in the bottom panel.

I added a prompt, selected a model, and "Generate" resulted in
```
18:39:08.263 [Info] User local requested 4 images with model 'REALISTIC/CyberRealisticXL_v11.safetensors'...
18:39:08.268 [Warning] [BackendHandler] No backends match the request! Cannot generate anything. Backends refused for the following reason(s):
- Request requires model 'REALISTIC/CyberRealisticXL_v11.safetensors' but the backend does not have that model
18:39:08.269 [Error] [BackendHandler] Backend request #1 failed: System.InvalidOperationException: No backends match the settings of the request given! Backends refused for the following reason(s):
- Request requires model 'REALISTIC/CyberRealisticXL_v11.safetensors' but the backend does not have that model
```

Then, I clicked on the model and manually chose "Load Now", which resulted in
```
18:39:46.100 [Error] Error loading model on backend 0 (ComfyUI Self-Starting): System.IO.InvalidDataException: ComfyUI errored: {
  "error": {
    "type": "prompt_outputs_failed_validation",
    "message": "Prompt outputs failed validation",
    "details": "",
    "extra_info": {}
  },
  "node_errors": {
    "4": {
      "errors": [
        {
          "type": "value_not_in_list",
          "message": "Value not in list",
          "details": "ckpt_name: 'REALISTIC/CyberRealisticXL_v11.safetensors' not in []",
          "extra_info": {
            "input_name": "ckpt_name",
            "input_config": [
              []
            ],
            "received_value": "REALISTIC/CyberRealisticXL_v11.safetensors"
          }
        }
      ],
      "dependent_outputs": [
        "9"
      ],
      "class_type": "CheckpointLoaderSimple"
    }
  }
}
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in D:\AI\SD\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 228
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.LoadModel(T2IModel model) in D:\AI\SD\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 751
   at StableSwarmUI.Backends.BackendHandler.LoadModelOnAll(T2IModel model, Func`2 filter) in D:\AI\SD\StableSwarmUI\src\Backends\BackendHandler.cs:line 613
18:39:46.101 [Warning] Tried 1 backends but none were able to load model 'REALISTIC/CyberRealisticXL_v11.safetensors'
```

It happens with all the models. All of them are SD XL based.

**Comment by mcmonkey4eva** [comment]
That looks like path handling got mixed -- it'll probably fix itself after a restart?
