### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by matthill** [Stability-AI/StableSwarmUI#362]
https://github.com/Stability-AI/StableSwarmUI/blame/0635d14b65f49a65d1585359bc4ba55fbdc1006e/src/Backends/NetworkBackendUtils.cs#L465

During install, this error occurs:

16:32:30.269 [Init] [Installer] Enabling ComfyUI...
16:32:30.270 [Init] [Installer] Downloading model from 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors'... please wait...
16:32:30.270 [Init] Initializing backend #0 - ComfyUI Self-Starting...
Unhandled exception. System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at StableSwarmUI.Backends.NetworkBackendUtils.<>c__DisplayClass13_0.<ReportLogsFromProcess>g__MonitorErrLoop|3() in /storage/projects/stable-swarm-webui/StableSwarmUI/src/Backends/NetworkBackendUtils.cs:line 465
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by mcmonkey4eva** [comment]
That error doesn't break the install, it just makes a mess in logs -- above commit fixes it to handle the edge case there cleanly
