### ISSUE TITLE
Preset import not working

### ISSUE THREAD

**Issue by begin2** [Stability-AI/StableSwarmUI#364]
Preset import not working.
I make all steps from manual:

- Download this file: [SDXL Official Presets.json](https://github.com/Stability-AI/StableSwarmUI/releases/download/0.5.6-Alpha/SDXL.Official.Presets.json) and save it somewhere (anywhere, desktop is fine)
- Open StableSwarmUI and open the `Presets` tab at the bottom
- Click on the `Import Presets` button
- drag the presets file in to the box that appears
- Click the `Import` button at the bottom
- close the box, look at your presets list - there is now a folder labeled `sdxlofficial` on the side. Click into that.

and got errors:
08:57:02.255 [Error] [WebAPI] Error handling API request '/API/AddNewPreset' for user 'local': Internal exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at FreneticUtilities.FreneticExtensions.StringExtensions.ToLowerFast(String input)
   at StableSwarmUI.Accounts.User.GetPreset(String name) in H:\Stable_Diffusion\Data\Packages\StableSwarmUI\src\Accounts\User.cs:line 117
   at StableSwarmUI.WebAPI.BasicAPIFeatures.AddNewPreset(Session session, String title, String description, JObject raw, String preview_image, Boolean is_edit, String editing) in H:\Stable_Diffusion\Data\Packages\StableSwarmUI\src\WebAPI\BasicAPIFeatures.cs:line 329
   at StableSwarmUI.WebAPI.API.HandleAsyncRequest(HttpContext context) in H:\Stable_Diffusion\Data\Packages\StableSwarmUI\src\WebAPI\API.cs:line 124
08:57:02.255 [Error] [WebAPI] Error handling API request '/API/AddNewPreset' for user 'local': Internal exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at FreneticUtilities.FreneticExtensions.StringExtensions.ToLowerFast(String input)
   at StableSwarmUI.Accounts.User.GetPreset(String name) in H:\Stable_Diffusion\Data\Packages\StableSwarmUI\src\Accounts\User.cs:line 117
   at StableSwarmUI.WebAPI.BasicAPIFeatures.AddNewPreset(Session session, String title, String description, JObject raw, String preview_image, Boolean is_edit, String editing) in H:\Stable_Diffusion\Data\Packages\StableSwarmUI\src\WebAPI\BasicAPIFeatures.cs:line 329
   at StableSwarmUI.WebAPI.API.HandleAsyncRequest(HttpContext context) in H:\Stable_Diffusion\Data\Packages\StableSwarmUI\src\WebAPI\API.cs:line 124

can you fix this please ? 
btw. where is presets stored on disk ? I reinstall new version and it be good to move old created presets to new install version.

**Comment by mcmonkey4eva** [comment]
Ah, oops, looks like Overwrite option when importing presets was mishandled -- fixed.

User data by default is stored in `(Swarm)/Data/Users.ldb` (a [LiteDB](https://www.litedb.org/) file). When transferring installs you'd want to transfer your Data directory and Models and whatever else.

btw just to be sure: you don't need to reinstall for updates, you can update in-place, there's even a UI button under the Server tab for update-and-restart

**Comment by begin2** [comment]
thanks, now presets import is working properly :)
