### ISSUE TITLE
Video generation: Cannot execute because node SwarmSaveAnimationWS does not exist

### ISSUE THREAD

**Issue by powellnorma** [Stability-AI/StableSwarmUI#366]
Followed https://github.com/Stability-AI/StableSwarmUI/blob/master/docs//Features/Video.md - But after the model got loaded, I get a popup with this error:

```
Invalid data: ComfyUI errored: {
  "error": {
    "type": "invalid_prompt",
    "message": "Cannot execute because node SwarmSaveAnimationWS does not exist.",
    "details": "Node ID '#105'",
    "extra_info": {}
  },
  "node_errors": []
}
```

**Comment by powellnorma** [comment]
Maybe it has to do with me using `SWARM_NO_VENV` ? Do I need to install additional pip packages?

**Comment by powellnorma** [comment]
After `pip install imageio-ffmpeg opencv-python-headless rembg` I still see in the logs:

```
Traceback (most recent call last):
  File "/content/StableSwarmUI/dlbackend/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/__init__.py", line 1, in <module>
    from . import SwarmRemBg, SwarmSaveAnimationWS, SwarmYolo
  File "/content/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/SwarmYolo.py", line 4, in <module>
    from ultralytics import YOLO
ModuleNotFoundError: No module named 'ultralytics'
```

Would it be possible to have a requirements.txt that contains everything needed?

**Comment by powellnorma** [comment]
Now I get this error:

```
Traceback (most recent call last):
  File "/content/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/StableSwarmUI/dlbackend/ComfyUI/nodes.py", line 57, in encode
    tokens = clip.tokenize(text)
AttributeError: 'NoneType' object has no attribute 'tokenize'
```

**Comment by powellnorma** [comment]
Ok, the last error was due to me having selected the video model in the model tab, see https://github.com/comfyanonymous/ComfyUI/issues/2119#issuecomment-1836977879

So this was enough to fix the initial problem: `pip install -r ./StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ExtraNodes/SwarmComfyExtra/requirements.txt`

Thank you for this project! :)

**Comment by mcmonkey4eva** [comment]
Ah yep. Normally swarm autoinstalls dependencies for you, but if you have a custom environment you do need to pip install manually like that yes
