### ISSUE TITLE
FACEID v2 Error: Invalid operation: ComfyUI execution error: insightface model is required for FaceID models

### ISSUE THREAD

**Issue by FemBoxbrawl** [Stability-AI/StableSwarmUI#372]
I cannot use FACEIDv2 because it gives me that error

![Screenshot 2024-06-05 113408](https://github.com/Stability-AI/StableSwarmUI/assets/129459206/7f83a3ee-5baf-4940-b21b-104b2dd89e1c)

**Comment by FemBoxbrawl** [comment]
> Did you let Swarm install comfy and the IP-Adapter nodepack, or did you install it manually? The Swarm installer for IP-Adapter should automatically install `insightface`

I let Swarm install the models automatically

**Comment by mcmonkey4eva** [comment]
That's a python package dependency not a model

Could you restart swarm, and open server -> logs -> Debug, wait for the "backends are loading..." message at the top to go away, and then copy/paste the logs to here?
I'm expecting a debug message like `Installing 'insightface' for ComfyUI...` (it should notice the required module is missing and re-attempt to install) and debug messages that follow it that explain what's breaking.

**Comment by FemBoxbrawl** [comment]
maybe it has to do with me having some other custom face node for comfy installed? i am not sure.


here:


2024-06-05 12:10:23.412 [Init] === StableSwarmUI v0.6.4.0 Starting at 2024-06-05 12:10:23 ===
2024-06-05 12:10:23.767 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
2024-06-05 12:10:23.783 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
2024-06-05 12:10:23.784 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2024-06-05 12:10:23.785 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2024-06-05 12:10:23.787 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2024-06-05 12:10:23.788 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2024-06-05 12:10:23.789 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2024-06-05 12:10:23.847 [Init] Parsing command line...
2024-06-05 12:10:23.849 [Init] Loading settings file...
2024-06-05 12:10:23.896 [Init] Re-saving settings file...
2024-06-05 12:10:23.914 [Init] Applying command line settings...
2024-06-05 12:10:24.156 [Init] Prepping options...
2024-06-05 12:10:24.312 [Info] Swarm is up to date! Version 0.6.4.0 is the latest.
2024-06-05 12:10:24.506 [Init] Loading models list...
2024-06-05 12:10:25.304 [Init] Loading backends...
2024-06-05 12:10:25.306 [Init] Loading backends from file...
2024-06-05 12:10:25.320 [Init] Prepping API...
2024-06-05 12:10:25.322 [Init] Initializing backend #0 - ComfyUI Self-Starting...
2024-06-05 12:10:25.323 [Init] Backend request handler loop ready...
2024-06-05 12:10:25.325 [Init] Prepping webserver...
2024-06-05 12:10:26.124 [Init] Scan for web extensions...
2024-06-05 12:10:26.244 [Init] Readying extensions for launch...
2024-06-05 12:10:26.247 [Init] Launching server...
2024-06-05 12:10:26.247 [Init] Starting webserver on http://localhost:7801
2024-06-05 12:10:26.307 [Init] Program is running.
2024-06-05 12:10:26.823 [Init] Launch web browser...
2024-06-05 12:10:27.599 [Info] Creating new admin session 'local' for ::1
2024-06-05 12:10:36.921 [Info] Self-Start ComfyUI (Git Pull) exited expectedly but with unexpected exit code 1
2024-06-05 12:10:37.154 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
2024-06-05 12:10:56.175 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
2024-06-05 12:10:56.180 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 1879, in load_custom_node
2024-06-05 12:10:56.181 [Warning] ComfyUI-0 on port 7821 stderr:     module_spec.loader.exec_module(module)
2024-06-05 12:10:56.182 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-06-05 12:10:56.183 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-06-05 12:10:56.183 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-FaceSwap\__init__.py", line 4, in <module>
2024-06-05 12:10:56.184 [Warning] ComfyUI-0 on port 7821 stderr:     from .FaceSwapNode import FaceSwapNode
2024-06-05 12:10:56.185 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-FaceSwap\FaceSwapNode.py", line 1, in <module>
2024-06-05 12:10:56.185 [Warning] ComfyUI-0 on port 7821 stderr:     import insightface
2024-06-05 12:10:56.186 [Warning] ComfyUI-0 on port 7821 stderr: ModuleNotFoundError: No module named 'insightface'
2024-06-05 12:10:56.187 [Warning] ComfyUI-0 on port 7821 stderr: 
2024-06-05 12:11:12.750 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
2024-06-05 12:11:12.752 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
2024-06-05 12:11:12.763 [Warning] ComfyUI-0 on port 7821 stderr:     hosts = await self._resolve_host(host, port, traces=traces)
2024-06-05 12:11:12.763 [Warning] ComfyUI-0 on port 7821 stderr:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.764 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\connector.py", line 880, in _resolve_host
2024-06-05 12:11:12.765 [Warning] ComfyUI-0 on port 7821 stderr:     return await asyncio.shield(resolved_host_task)
2024-06-05 12:11:12.765 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.770 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
2024-06-05 12:11:12.771 [Warning] ComfyUI-0 on port 7821 stderr:     addrs = await self._resolver.resolve(host, port, family=self._family)
2024-06-05 12:11:12.772 [Warning] ComfyUI-0 on port 7821 stderr:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.772 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\resolver.py", line 33, in resolve
2024-06-05 12:11:12.779 [Warning] ComfyUI-0 on port 7821 stderr:     infos = await self._loop.getaddrinfo(
2024-06-05 12:11:12.781 [Warning] ComfyUI-0 on port 7821 stderr:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.782 [Warning] ComfyUI-0 on port 7821 stderr:   File "asyncio\base_events.py", line 868, in getaddrinfo
2024-06-05 12:11:12.783 [Warning] ComfyUI-0 on port 7821 stderr:   File "concurrent\futures\thread.py", line 58, in run
2024-06-05 12:11:12.785 [Warning] ComfyUI-0 on port 7821 stderr:   File "socket.py", line 962, in getaddrinfo
2024-06-05 12:11:12.786 [Warning] ComfyUI-0 on port 7821 stderr: socket.gaierror: [Errno 11001] getaddrinfo failed
2024-06-05 12:11:12.787 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
2024-06-05 12:11:12.788 [Warning] ComfyUI-0 on port 7821 stderr:   File "threading.py", line 1045, in _bootstrap_inner
2024-06-05 12:11:12.789 [Warning] ComfyUI-0 on port 7821 stderr:   File "threading.py", line 982, in run
2024-06-05 12:11:12.790 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1667, in <lambda>
2024-06-05 12:11:12.819 [Warning] ComfyUI-0 on port 7821 stderr:     threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
2024-06-05 12:11:12.822 [Warning] ComfyUI-0 on port 7821 stderr:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.823 [Warning] ComfyUI-0 on port 7821 stderr:   File "asyncio\runners.py", line 190, in run
2024-06-05 12:11:12.823 [Warning] ComfyUI-0 on port 7821 stderr:   File "asyncio\runners.py", line 118, in run
2024-06-05 12:11:12.826 [Warning] ComfyUI-0 on port 7821 stderr:   File "asyncio\base_events.py", line 654, in run_until_complete
2024-06-05 12:11:12.826 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1664, in default_cache_update
2024-06-05 12:11:12.827 [Warning] ComfyUI-0 on port 7821 stderr:     await asyncio.gather(a, b, c, d, e)
2024-06-05 12:11:12.828 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1651, in get_cache
2024-06-05 12:11:12.829 [Warning] ComfyUI-0 on port 7821 stderr:     json_obj = await core.get_data(uri, True)
2024-06-05 12:11:12.830 [Warning] ComfyUI-0 on port 7821 stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.830 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 583, in get_data
2024-06-05 12:11:12.835 [Warning] ComfyUI-0 on port 7821 stderr:     async with session.get(uri) as resp:
2024-06-05 12:11:12.836 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
2024-06-05 12:11:12.848 [Warning] ComfyUI-0 on port 7821 stderr:     self._resp = await self._coro
2024-06-05 12:11:12.852 [Warning] ComfyUI-0 on port 7821 stderr:                  ^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.853 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\client.py", line 581, in _request
2024-06-05 12:11:12.854 [Warning] ComfyUI-0 on port 7821 stderr:     conn = await self._connector.connect(
2024-06-05 12:11:12.855 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.856 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\connector.py", line 544, in connect
2024-06-05 12:11:12.857 [Warning] ComfyUI-0 on port 7821 stderr:     proto = await self._create_connection(req, traces, timeout)
2024-06-05 12:11:12.860 [Warning] ComfyUI-0 on port 7821 stderr:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.860 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
2024-06-05 12:11:12.861 [Warning] ComfyUI-0 on port 7821 stderr:     _, proto = await self._create_direct_connection(req, traces, timeout)
2024-06-05 12:11:12.865 [Warning] ComfyUI-0 on port 7821 stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-05 12:11:12.866 [Warning] ComfyUI-0 on port 7821 stderr:   File "H:\AI\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
2024-06-05 12:11:12.867 [Warning] ComfyUI-0 on port 7821 stderr:     raise ClientConnectorError(req.connection_key, exc) from exc
2024-06-05 12:11:12.868 [Warning] ComfyUI-0 on port 7821 stderr: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [getaddrinfo failed]
2024-06-05 12:11:27.749 [Warning] ComfyUI-0 on port 7821 stderr: 
2024-06-05 12:11:32.049 [Init] Self-Start ComfyUI-0 on port 7821 started.

**Comment by mcmonkey4eva** [comment]
Ah, yeah, that error is not from Swarm's IP-Adapter support that is installed, that is you yourself separately installed `ComfyUI-FaceSwap` and did not get its dependencies.

The easiest solution is just to drag an image into the Swarm generate box so you get the recommendation to let Swarm install IP-Adapter for you to pop up on the left, and let that run and it will install insightface and coincidentally helpfully fix the other node that needs it too.

Or you can ask the developer of `ComfyUI-FaceSwap` or presumably Manager if you used that to install it why the dependency wasn't installed
