### ISSUE TITLE
Image preview during generation is not working

### ISSUE THREAD

**Issue by Shangooriginal** [Stability-AI/StableSwarmUI#379]
I have enabled the preview option in the backend. Am I missing another feature or function to turn on the image preview?
Here's the blank image of the preview when generating image
![Screenshot 2024-06-09 144826](https://github.com/Stability-AI/StableSwarmUI/assets/105495790/6524e641-5684-4468-b649-14f707c85ae3)

Here's the reference that I have enabled the image preview in the backend.
![Screenshot 2024-06-09 144912](https://github.com/Stability-AI/StableSwarmUI/assets/105495790/92124957-2eeb-4c39-a024-e43021b9f393)

**Comment by mcmonkey4eva** [comment]
So first things first try the obvious prodding and/or kicking the machine -- make sure everything's updated, you're not running anything in too unusual a way, and try restarting Swarm

If it doesn't fix itself: can you post more information about your setup?

If you generate a full image and post a screenshot of the parameters list that'd cover most info

Also, what GPU/OS are you using? eg if you're on an AMD card on windows there's known issues with DirectML previews

**Comment by Joshua19770704** [comment]
Hi, dear mcmonkey, I have the same problem. At first, the preview worked fine, but the segmentation didn't work, so I had to update the  Transformer to the newest version of 4.47.1. After the update, the segmentation worked fine, but the preview didn't show up.  My OS is Windows 11, RTX3060 12G Vram.  How do we solve this problem? Thanks for your help. 

![{7D33989D-9FF0-4C63-A5E5-D869D688FB1C}](https://github.com/user-attachments/assets/5a1e0446-b44e-4c42-9591-5f77e688ed1b)


19:25:44.562 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
19:25:44.563 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
19:25:44.563 [Warning] [ComfyUI-0/STDERR]     return importlib.import_module("." + module_name, self.__name__)
19:25:44.564 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\importlib\__init__.py", line 126, in import_module
19:25:44.564 [Warning] [ComfyUI-0/STDERR]     return _bootstrap._gcd_import(name[level:], package, level)
19:25:44.565 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
19:25:44.565 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
19:25:44.566 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
19:25:44.566 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
19:25:44.567 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
19:25:44.567 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
19:25:44.567 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\loaders\unet.py", line 46, in <module>
19:25:44.568 [Warning] [ComfyUI-0/STDERR]     from .lora_pipeline import LORA_WEIGHT_NAME, LORA_WEIGHT_NAME_SAFE, TEXT_ENCODER_NAME, UNET_NAME
19:25:44.568 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\loaders\lora_pipeline.py", line 36, in <module>
19:25:44.569 [Warning] [ComfyUI-0/STDERR]     from .lora_base import LoraBaseMixin
19:25:44.569 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\loaders\lora_base.py", line 47, in <module>
19:25:44.570 [Warning] [ComfyUI-0/STDERR]     from peft.tuners.tuners_utils import BaseTunerLayer
19:25:44.570 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\__init__.py", line 22, in <module>
19:25:44.571 [Warning] [ComfyUI-0/STDERR]     from .auto import (
19:25:44.572 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\auto.py", line 32, in <module>
19:25:44.572 [Warning] [ComfyUI-0/STDERR]     from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
19:25:44.573 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\mapping.py", line 22, in <module>
19:25:44.573 [Warning] [ComfyUI-0/STDERR]     from peft.tuners.xlora.model import XLoraModel
19:25:44.574 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
19:25:44.574 [Warning] [ComfyUI-0/STDERR]     from .lora import LoraConfig, LoraModel, LoftQConfig, LoraRuntimeConfig
19:25:44.575 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\__init__.py", line 20, in <module>
19:25:44.575 [Warning] [ComfyUI-0/STDERR]     from .model import LoraModel
19:25:44.576 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\model.py", line 50, in <module>
19:25:44.576 [Warning] [ComfyUI-0/STDERR]     from .awq import dispatch_awq
19:25:44.576 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\awq.py", line 26, in <module>
19:25:44.577 [Warning] [ComfyUI-0/STDERR]     from awq.modules.linear import WQLinear_GEMM
19:25:44.577 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\__init__.py", line 2, in <module>
19:25:44.577 [Warning] [ComfyUI-0/STDERR]     from awq.models.auto import AutoAWQForCausalLM
19:25:44.578 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\__init__.py", line 1, in <module>
19:25:44.578 [Warning] [ComfyUI-0/STDERR]     from .mpt import MptAWQForCausalLM
19:25:44.579 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\mpt.py", line 1, in <module>
19:25:44.579 [Warning] [ComfyUI-0/STDERR]     from .base import BaseAWQForCausalLM
19:25:44.580 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\base.py", line 13, in <module>
19:25:44.580 [Warning] [ComfyUI-0/STDERR]     from transformers.modeling_utils import shard_checkpoint
19:25:44.581 [Warning] [ComfyUI-0/STDERR] ImportError: cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\modeling_utils.py)
19:25:44.582 [Warning] [ComfyUI-0/STDERR]
19:25:44.582 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
19:25:44.583 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
19:25:44.583 [Warning] [ComfyUI-0/STDERR]     return importlib.import_module("." + module_name, self.__name__)
19:25:44.584 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\importlib\__init__.py", line 126, in import_module
19:25:44.584 [Warning] [ComfyUI-0/STDERR]     return _bootstrap._gcd_import(name[level:], package, level)
19:25:44.584 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
19:25:44.585 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
19:25:44.585 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
19:25:44.585 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
19:25:44.586 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
19:25:44.586 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
19:25:44.586 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
19:25:44.587 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
19:25:44.587 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
19:25:44.588 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
19:25:44.588 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\autoencoders\__init__.py", line 1, in <module>
19:25:44.589 [Warning] [ComfyUI-0/STDERR]     from .autoencoder_asym_kl import AsymmetricAutoencoderKL
19:25:44.589 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_asym_kl.py", line 23, in <module>
19:25:44.591 [Warning] [ComfyUI-0/STDERR]     from .vae import DecoderOutput, DiagonalGaussianDistribution, Encoder, MaskConditionDecoder
19:25:44.591 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\autoencoders\vae.py", line 25, in <module>
19:25:44.592 [Warning] [ComfyUI-0/STDERR]     from ..unets.unet_2d_blocks import (
19:25:44.592 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\unets\__init__.py", line 6, in <module>
19:25:44.593 [Warning] [ComfyUI-0/STDERR]     from .unet_2d import UNet2DModel
19:25:44.593 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\unets\unet_2d.py", line 24, in <module>
19:25:44.594 [Warning] [ComfyUI-0/STDERR]     from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
19:25:44.594 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 36, in <module>
19:25:44.595 [Warning] [ComfyUI-0/STDERR]     from ..transformers.dual_transformer_2d import DualTransformer2DModel
19:25:44.595 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\transformers\__init__.py", line 13, in <module>
19:25:44.595 [Warning] [ComfyUI-0/STDERR]     from .prior_transformer import PriorTransformer
19:25:44.596 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\transformers\prior_transformer.py", line 9, in <module>
19:25:44.596 [Warning] [ComfyUI-0/STDERR]     from ...loaders import PeftAdapterMixin, UNet2DConditionLoadersMixin
19:25:44.597 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
19:25:44.597 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
19:25:44.597 [Warning] [ComfyUI-0/STDERR]     module = self._get_module(self._class_to_module[name])
19:25:44.598 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
19:25:44.598 [Warning] [ComfyUI-0/STDERR]     raise RuntimeError(
19:25:44.598 [Warning] [ComfyUI-0/STDERR] RuntimeError: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
19:25:44.599 [Warning] [ComfyUI-0/STDERR] cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\modeling_utils.py)
19:25:44.600 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
19:25:44.601 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\nodes.py", line 2092, in load_custom_node
19:25:44.601 [Warning] [ComfyUI-0/STDERR]     module_spec.loader.exec_module(module)
19:25:44.602 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
19:25:44.602 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
19:25:44.602 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 2, in <module>
19:25:44.603 [Warning] [ComfyUI-0/STDERR]     from .model_loading import NODE_CLASS_MAPPINGS as MODEL_CLASS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_DISPLAY
19:25:44.603 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper\model_loading.py", line 40, in <module>
19:25:44.603 [Warning] [ComfyUI-0/STDERR]     from diffusers.models import AutoencoderKLCogVideoX
19:25:44.604 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
19:25:44.604 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
19:25:44.605 [Warning] [ComfyUI-0/STDERR]     module = self._get_module(self._class_to_module[name])
19:25:44.605 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
19:25:44.606 [Warning] [ComfyUI-0/STDERR]     raise RuntimeError(
19:25:44.606 [Warning] [ComfyUI-0/STDERR] RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
19:25:44.607 [Warning] [ComfyUI-0/STDERR] Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
19:25:59.787 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
19:25:59.788 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\utils\import_utils.py", line 1793, in _get_module
19:25:59.788 [Warning] [ComfyUI-0/STDERR]     return importlib.import_module("." + module_name, self.__name__)
19:25:59.788 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\importlib\__init__.py", line 126, in import_module
19:25:59.788 [Warning] [ComfyUI-0/STDERR]     return _bootstrap._gcd_import(name[level:], package, level)
19:25:59.788 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
19:25:59.789 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
19:25:59.789 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
19:25:59.789 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
19:25:59.789 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
19:25:59.789 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
19:25:59.790 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\trainer.py", line 226, in <module>
19:25:59.790 [Warning] [ComfyUI-0/STDERR]     from peft import PeftModel
19:25:59.790 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\__init__.py", line 22, in <module>
19:25:59.790 [Warning] [ComfyUI-0/STDERR]     from .auto import (
19:25:59.791 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\auto.py", line 32, in <module>
19:25:59.791 [Warning] [ComfyUI-0/STDERR]     from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
19:25:59.792 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\mapping.py", line 22, in <module>
19:25:59.792 [Warning] [ComfyUI-0/STDERR]     from peft.tuners.xlora.model import XLoraModel
19:25:59.793 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
19:25:59.794 [Warning] [ComfyUI-0/STDERR]     from .lora import LoraConfig, LoraModel, LoftQConfig, LoraRuntimeConfig
19:25:59.794 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\__init__.py", line 20, in <module>
19:25:59.795 [Warning] [ComfyUI-0/STDERR]     from .model import LoraModel
19:25:59.795 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\model.py", line 50, in <module>
19:25:59.798 [Warning] [ComfyUI-0/STDERR]     from .awq import dispatch_awq
19:25:59.798 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\awq.py", line 26, in <module>
19:25:59.799 [Warning] [ComfyUI-0/STDERR]     from awq.modules.linear import WQLinear_GEMM
19:25:59.799 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\__init__.py", line 2, in <module>
19:25:59.800 [Warning] [ComfyUI-0/STDERR]     from awq.models.auto import AutoAWQForCausalLM
19:25:59.800 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\__init__.py", line 1, in <module>
19:25:59.801 [Warning] [ComfyUI-0/STDERR]     from .mpt import MptAWQForCausalLM
19:25:59.801 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\mpt.py", line 1, in <module>
19:25:59.802 [Warning] [ComfyUI-0/STDERR]     from .base import BaseAWQForCausalLM
19:25:59.802 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\base.py", line 13, in <module>
19:25:59.803 [Warning] [ComfyUI-0/STDERR]     from transformers.modeling_utils import shard_checkpoint
19:25:59.803 [Warning] [ComfyUI-0/STDERR] ImportError: cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\modeling_utils.py)
19:25:59.804 [Warning] [ComfyUI-0/STDERR]
19:25:59.804 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
19:25:59.805 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\nodes.py", line 2092, in load_custom_node
19:25:59.807 [Warning] [ComfyUI-0/STDERR]     module_spec.loader.exec_module(module)
19:25:59.808 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
19:25:59.808 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
19:25:59.809 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_BadgerTools\__init__.py", line 11, in <module>
19:25:59.809 [Warning] [ComfyUI-0/STDERR]     from .videoCut import getCutList, video_to_frames, cutToDir, frames_to_video
19:25:59.810 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_BadgerTools\videoCut.py", line 6, in <module>
19:25:59.810 [Warning] [ComfyUI-0/STDERR]     from sentence_transformers import util
19:25:59.811 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\sentence_transformers\__init__.py", line 18, in <module>
19:25:59.811 [Warning] [ComfyUI-0/STDERR]     from sentence_transformers.trainer import SentenceTransformerTrainer
19:25:59.812 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\sentence_transformers\trainer.py", line 12, in <module>
19:25:59.812 [Warning] [ComfyUI-0/STDERR]     from transformers import EvalPrediction, PreTrainedTokenizerBase, Trainer, TrainerCallback
19:25:59.813 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
19:25:59.813 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\utils\import_utils.py", line 1781, in __getattr__
19:25:59.814 [Warning] [ComfyUI-0/STDERR]     module = self._get_module(self._class_to_module[name])
19:25:59.815 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\utils\import_utils.py", line 1795, in _get_module
19:25:59.815 [Warning] [ComfyUI-0/STDERR]     raise RuntimeError(
19:25:59.817 [Warning] [ComfyUI-0/STDERR] RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
19:25:59.818 [Warning] [ComfyUI-0/STDERR] cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\modeling_utils.py)
19:26:02.227 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
19:26:02.228 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\nodes.py", line 2092, in load_custom_node
19:26:02.228 [Warning] [ComfyUI-0/STDERR]     module_spec.loader.exec_module(module)
19:26:02.228 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
19:26:02.228 [Warning] [ComfyUI-0/STDERR]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
19:26:02.229 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\OmniGen-ComfyUI\__init__.py", line 7, in <module>
19:26:02.229 [Warning] [ComfyUI-0/STDERR]     from .nodes import OmniGenNode
19:26:02.229 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\OmniGen-ComfyUI\nodes.py", line 7, in <module>
19:26:02.229 [Warning] [ComfyUI-0/STDERR]     from OmniGen import OmniGenPipeline
19:26:02.229 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\OmniGen-ComfyUI\OmniGen\__init__.py", line 4, in <module>
19:26:02.230 [Warning] [ComfyUI-0/STDERR]     from .pipeline import OmniGenPipeline
19:26:02.230 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\custom_nodes\OmniGen-ComfyUI\OmniGen\pipeline.py", line 10, in <module>
19:26:02.231 [Warning] [ComfyUI-0/STDERR]     from peft import LoraConfig, PeftModel
19:26:02.231 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\__init__.py", line 22, in <module>
19:26:02.232 [Warning] [ComfyUI-0/STDERR]     from .auto import (
19:26:02.232 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\auto.py", line 32, in <module>
19:26:02.233 [Warning] [ComfyUI-0/STDERR]     from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
19:26:02.233 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\mapping.py", line 22, in <module>
19:26:02.233 [Warning] [ComfyUI-0/STDERR]     from peft.tuners.xlora.model import XLoraModel
19:26:02.234 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
19:26:02.234 [Warning] [ComfyUI-0/STDERR]     from .lora import LoraConfig, LoraModel, LoftQConfig, LoraRuntimeConfig
19:26:02.235 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\__init__.py", line 20, in <module>
19:26:02.235 [Warning] [ComfyUI-0/STDERR]     from .model import LoraModel
19:26:02.236 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\model.py", line 50, in <module>
19:26:02.238 [Warning] [ComfyUI-0/STDERR]     from .awq import dispatch_awq
19:26:02.238 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\peft\tuners\lora\awq.py", line 26, in <module>
19:26:02.239 [Warning] [ComfyUI-0/STDERR]     from awq.modules.linear import WQLinear_GEMM
19:26:02.239 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\__init__.py", line 2, in <module>
19:26:02.240 [Warning] [ComfyUI-0/STDERR]     from awq.models.auto import AutoAWQForCausalLM
19:26:02.240 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\__init__.py", line 1, in <module>
19:26:02.241 [Warning] [ComfyUI-0/STDERR]     from .mpt import MptAWQForCausalLM
19:26:02.241 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\mpt.py", line 1, in <module>
19:26:02.241 [Warning] [ComfyUI-0/STDERR]     from .base import BaseAWQForCausalLM
19:26:02.242 [Warning] [ComfyUI-0/STDERR]   File "D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\awq\models\base.py", line 13, in <module>
19:26:02.242 [Warning] [ComfyUI-0/STDERR]     from transformers.modeling_utils import shard_checkpoint
19:26:02.243 [Warning] [ComfyUI-0/STDERR] ImportError: cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (D:\SUPER_SD\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\modeling_utils.py)
19:26:02.243 [Warning] [ComfyUI-0/STDERR]
19:26:06.610 [Init] Self-Start ComfyUI-0 on port 7821 started.
19:26:10.215 [Warning] Failed to load metadata for clipseg/models--CIDAS--clipseg-rd64-refined/.no_exist/583b388deb98a04feb3e1f816dcdb8f3062ee205/model.safetensors:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.Stream.ReadAtLeastCore(Span`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream)
   at System.IO.Stream.ReadExactly(Byte[] buffer, Int32 offset, Int32 count)
   at SwarmUI.Text2Image.T2IModel.GetSafetensorsHeaderFrom(String modelPath) in D:\SUPER_SD\SwarmUI\src\Text2Image\T2IModel.cs:line 266
   at SwarmUI.Text2Image.T2IModelHandler.LoadMetadata(T2IModel model) in D:\SUPER_SD\SwarmUI\src\Text2Image\T2IModelHandler.cs:line 373
   at SwarmUI.Text2Image.T2IModelHandler.<>c__DisplayClass25_0.<AddAllFromFolder>b__1(String file) in D:\SUPER_SD\SwarmUI\src\Text2Image\T2IModelHandler.cs:line 622

**Comment by mcmonkey4eva** [comment]
Did you miss the readme migration notice? https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#migration-notice
https://github.com/mcmonkeyprojects/SwarmUI/discussions/2

**Comment by Joshua19770704** [comment]
Yes, I do install and use the SwarmUI now. I just searched the Internet to get here. By the way, after I double-clicked  the “update-windows.bat”, the preview was back! Thank you so much for your great work! This app is awesome! I love it!

![{A7C38B08-A508-4387-A161-92B4C754D783}](https://github.com/user-attachments/assets/5fa3b753-788e-41c8-b9e0-8ff4decfd29c)
