### ISSUE TITLE
After startup, unable to enter the ComfyUI workflow

### ISSUE THREAD

**Issue by js027** [Stability-AI/StableSwarmUI#410]
Tip: Unable to load module: Apache2. The server may still be loading.
May I ask everyone how to modify this? Thank you!

**Comment by js027** [comment]
> 提示：无法加载模块：Apache2。服务器可能仍在加载中。 请问大家如何修改这个？谢谢！

2024-06-16 22:36:01.390 [Init] === StableSwarmUI v0.6.4.0 Starting at 2024-06-16 22:36:01 ===
2024-06-16 22:36:01.427 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
2024-06-16 22:36:01.433 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
2024-06-16 22:36:01.434 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2024-06-16 22:36:01.434 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2024-06-16 22:36:01.434 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2024-06-16 22:36:01.435 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2024-06-16 22:36:01.435 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2024-06-16 22:36:01.462 [Init] Parsing command line...
2024-06-16 22:36:01.463 [Init] Loading settings file...
2024-06-16 22:36:01.478 [Init] Re-saving settings file...
2024-06-16 22:36:01.491 [Init] Applying command line settings...
2024-06-16 22:36:01.512 [Init] Prepping options...
2024-06-16 22:36:01.608 [Init] Loading models list...
2024-06-16 22:36:01.642 [Init] Loading backends...
2024-06-16 22:36:01.643 [Init] Loading backends from file...
2024-06-16 22:36:01.645 [Init] Prepping API...
2024-06-16 22:36:01.645 [Init] Initializing backend #0 - ComfyUI Self-Starting...
2024-06-16 22:36:01.646 [Init] Backend request handler loop ready...
2024-06-16 22:36:01.647 [Init] Prepping webserver...
2024-06-16 22:36:01.785 [Init] Scan for web extensions...
2024-06-16 22:36:01.786 [Init] Readying extensions for launch...
2024-06-16 22:36:01.787 [Init] Launching server...
2024-06-16 22:36:01.787 [Init] Starting webserver on http://localhost:7801
2024-06-16 22:36:01.819 [Init] Program is running.
2024-06-16 22:36:01.957 [Info] Swarm is up to date! Version 0.6.4.0 is the latest.
2024-06-16 22:36:02.323 [Init] Launch web browser...
2024-06-16 22:36:02.956 [Info] Creating new admin session 'local' for ::1
2024-06-16 22:36:03.340 [Info] Self-Start comfy node pull exited expectedly but with unexpected exit code 1
2024-06-16 22:36:03.404 [Info] Self-Start ComfyUI (Git Pull) exited properly.
2024-06-16 22:36:03.442 [Info] Self-Start comfy node pull exited properly.
2024-06-16 22:36:04.515 [Info] Self-Start comfy node pull exited expectedly but with unexpected exit code 1
2024-06-16 22:36:04.633 [Info] Self-Start comfy node pull exited properly.
2024-06-16 22:36:04.659 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
2024-06-16 22:36:07.976 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
2024-06-16 22:36:07.977 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\nodes.py", line 1906, in load_custom_node
2024-06-16 22:36:07.978 [Warning] ComfyUI-0 on port 7821 stderr:     module_spec.loader.exec_module(module)
2024-06-16 22:36:07.979 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 936, in exec_module
2024-06-16 22:36:07.979 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 1073, in get_code
2024-06-16 22:36:07.979 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 1130, in get_data
2024-06-16 22:36:07.980 [Warning] ComfyUI-0 on port 7821 stderr: FileNotFoundError: [Errno 2] No such file or directory: 'E:\\StableSwarmUI_sd3\\src\\BuiltinExtensions\\ComfyUIBackend\\DLNodes\\sd-dynamic-thresholding\\__init__.py'
2024-06-16 22:36:07.980 [Warning] ComfyUI-0 on port 7821 stderr: 
2024-06-16 22:39:22.586 [Info] Creating new admin session 'local' for ::1

**Comment by mcmonkey4eva** [comment]
Please ensure you've installed swarm properly per the readme https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-windows

And update Swarm, there have been multiple improvements to debugging in the recent dev builds (0.6.4.1)

After updating, if things are still erroring, please check Server -> Logs -> Debug and post the debug log here

**Comment by js027** [comment]
Windows 11 Enterprise Edition, after installing the Apache 2.4 program and modifying the configuration, can independently start Apache 2 normally. You can now enter the ComfyUI workflow normally.

**Comment by js027** [comment]
Click on comfyworkflow and prompt "Unable to load module: Apache2." The server may still be loading The same file appeared again, appearing to be random and intermittent, and even restarting the computer did not work. Here are the logs:

""
""
"WARNING: YOU DID NOT CLONE FROM GIT. THIS WILL BREAK SOME SYSTEMS. PLEASE INSTALL PER THE README."
""
""
18:54:53.951 [Init] === StableSwarmUI v0.6.4.0 Starting at 2024-06-19 18:54:53 ===
18:54:54.083 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
18:54:54.089 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
18:54:54.089 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
18:54:54.090 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
18:54:54.090 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
18:54:54.090 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
18:54:54.090 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
18:54:54.119 [Init] Parsing command line...
18:54:54.120 [Init] Loading settings file...
18:54:54.142 [Init] Re-saving settings file...
18:54:54.155 [Init] Applying command line settings...
18:54:54.237 [Init] Prepping options...
18:54:54.432 [Init] Loading models list...
18:54:54.470 [Init] Loading backends...
18:54:54.471 [Init] Loading backends from file...
18:54:54.478 [Init] Prepping API...
18:54:54.478 [Init] Initializing backend #0 - ComfyUI Self-Starting...
18:54:54.479 [Init] Backend request handler loop ready...
18:54:54.479 [Init] Prepping webserver...
18:54:54.627 [Init] Scan for web extensions...
18:54:54.692 [Init] Readying extensions for launch...
18:54:54.693 [Init] Launching server...
18:54:54.693 [Init] Starting webserver on http://*:7801
18:54:54.731 [Init] Program is running.
18:54:54.815 [Info] Swarm is up to date! Version 0.6.4.0 is the latest.
18:54:55.238 [Init] Launch web browser...
18:54:56.128 [Info] Creating new admin session 'local' for ::1
18:54:56.135 [Info] Self-Start comfy node pull exited expectedly but with unexpected exit code 1
18:54:56.170 [Info] Self-Start comfy node pull exited properly.
18:54:56.192 [Info] Self-Start ComfyUI (Git Pull) exited properly.
18:54:57.371 [Info] Self-Start comfy node pull exited expectedly but with unexpected exit code 1
18:54:57.416 [Info] Self-Start comfy node pull exited properly.
18:54:57.443 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
18:55:10.095 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
18:55:10.096 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\nodes.py", line 1906, in load_custom_node
18:55:10.096 [Warning] ComfyUI-0 on port 7821 stderr:     module_spec.loader.exec_module(module)
18:55:10.097 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
18:55:10.098 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
18:55:10.099 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Crystools\__init__.py", line 10, in <module>
18:55:10.099 [Warning] ComfyUI-0 on port 7821 stderr:     from .core import version, logger
18:55:10.100 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Crystools\core\__init__.py", line 5, in <module>
18:55:10.100 [Warning] ComfyUI-0 on port 7821 stderr:     from .common import *
18:55:10.101 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Crystools\core\common.py", line 4, in <module>
18:55:10.102 [Warning] ComfyUI-0 on port 7821 stderr:     from deepdiff import DeepDiff
18:55:10.102 [Warning] ComfyUI-0 on port 7821 stderr: ModuleNotFoundError: No module named 'deepdiff'
18:55:10.103 [Warning] ComfyUI-0 on port 7821 stderr:
18:55:11.921 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
18:55:11.922 [Warning] ComfyUI-0 on port 7821 stderr:   File "threading.py", line 1045, in _bootstrap_inner
18:55:11.922 [Warning] ComfyUI-0 on port 7821 stderr:   File "threading.py", line 982, in run
18:55:11.923 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1679, in <lambda>
18:55:11.932 [Warning] ComfyUI-0 on port 7821 stderr:     threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
18:55:11.932 [Warning] ComfyUI-0 on port 7821 stderr:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
18:55:11.933 [Warning] ComfyUI-0 on port 7821 stderr:   File "asyncio\runners.py", line 190, in run
18:55:11.934 [Warning] ComfyUI-0 on port 7821 stderr:   File "asyncio\runners.py", line 118, in run
18:55:11.934 [Warning] ComfyUI-0 on port 7821 stderr:   File "asyncio\base_events.py", line 654, in run_until_complete
18:55:11.935 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1676, in default_cache_update
18:55:11.935 [Warning] ComfyUI-0 on port 7821 stderr:     await asyncio.gather(a, b, c, d, e)
18:55:11.936 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 1663, in get_cache
18:55:11.937 [Warning] ComfyUI-0 on port 7821 stderr:     json_obj = await core.get_data(uri, True)
18:55:11.937 [Warning] ComfyUI-0 on port 7821 stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
18:55:11.938 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 583, in get_data
18:55:11.942 [Warning] ComfyUI-0 on port 7821 stderr:     async with session.get(uri) as resp:
18:55:11.943 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\python_embeded\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
18:55:11.947 [Warning] ComfyUI-0 on port 7821 stderr: [comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
18:55:11.982 [Warning] ComfyUI-0 on port 7821 stderr: aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
18:55:21.534 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
18:55:21.534 [Warning] ComfyUI-0 on port 7821 stderr:   File "E:\StableSwarmUI_sd3\dlbackend\comfy\ComfyUI\nodes.py", line 1906, in load_custom_node
18:55:21.535 [Warning] ComfyUI-0 on port 7821 stderr:     module_spec.loader.exec_module(module)
18:55:21.536 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 936, in exec_module
18:55:21.536 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 1073, in get_code
18:55:21.536 [Warning] ComfyUI-0 on port 7821 stderr:   File "<frozen importlib._bootstrap_external>", line 1130, in get_data
18:55:21.536 [Warning] ComfyUI-0 on port 7821 stderr: FileNotFoundError: [Errno 2] No such file or directory: 'E:\\StableSwarmUI_sd3\\src\\BuiltinExtensions\\ComfyUIBackend\\DLNodes\\sd-dynamic-thresholding\\__init__.py'
18:55:21.537 [Warning] ComfyUI-0 on port 7821 stderr:
18:57:46.504 [Info] Creating new admin session 'local' for ::1
18:59:37.307 [Info] User local requested 1 image with model 'OfficialStableDiffusion/sd3_medium.safetensors'...
18:59:59.680 [Info] Creating new admin session 'local' for ::1

> Please ensure you've installed swarm properly per the readme https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#installing-on-windows
> 
> And update Swarm, there have been multiple improvements to debugging in the recent dev builds (0.6.4.1)
> 
> After updating, if things are still erroring, please check Server -> Logs -> Debug and post the debug log here

**Comment by mcmonkey4eva** [comment]
I don't know what you're doing there. Swarm & Comfy don't use apache. If you have it installed externally somewhere, you might be using an apache based redirection?
