### ISSUE TITLE
Error when loading kolors

### ISSUE THREAD

**Issue by atom-fox** [Stability-AI/StableSwarmUI#434]
02:28:44.121 [Warning] ComfyUI-0 on port 7821 stderr: !!! Exception during processing!!! ERROR: Could not detect model type of: D:\Desktop\codeTime\service\StableSwarmUI\Models\Stable-Diffusion\UNet\Kolors\diffusion_pytorch_model.fp16.safetensors
02:28:44.123 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
02:28:44.123 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\Desktop\codeTime\service\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 151, in recursive_execute
02:28:44.124 [Warning] ComfyUI-0 on port 7821 stderr:     output_data, output_ui = get_output_data(obj, input_data_all)
02:28:44.125 [Warning] ComfyUI-0 on port 7821 stderr:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:28:44.126 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\Desktop\codeTime\service\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 81, in get_output_data
02:28:44.126 [Warning] ComfyUI-0 on port 7821 stderr:     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
02:28:44.127 [Warning] ComfyUI-0 on port 7821 stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:28:44.127 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\Desktop\codeTime\service\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 74, in map_node_over_list
02:28:44.128 [Warning] ComfyUI-0 on port 7821 stderr:     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
02:28:44.128 [Warning] ComfyUI-0 on port 7821 stderr:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:28:44.129 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\Desktop\codeTime\service\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 518, in load_checkpoint
02:28:44.129 [Warning] ComfyUI-0 on port 7821 stderr:     out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
02:28:44.130 [Warning] ComfyUI-0 on port 7821 stderr:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
02:28:44.130 [Warning] ComfyUI-0 on port 7821 stderr:   File "D:\Desktop\codeTime\service\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\sd.py", line 497, in load_checkpoint_guess_config
02:28:44.131 [Warning] ComfyUI-0 on port 7821 stderr:     raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
02:28:44.131 [Warning] ComfyUI-0 on port 7821 stderr: RuntimeError: ERROR: Could not detect model type of: D:\Desktop\codeTime\service\StableSwarmUI\Models\Stable-Diffusion\UNet\Kolors\diffusion_pytorch_model.fp16.safetensors
02:28:44.132 [Warning] ComfyUI-0 on port 7821 stderr:
02:28:44.204 [Error] [BackendHandler] backend #0 failed to load model with error: System.AggregateException: One or more errors occurred. (ComfyUI execution error: ERROR: Could not detect model type of: D:\Desktop\codeTime\service\StableSwarmUI\Models\Stable-Diffusion\UNet\Kolors\diffusion_pytorch_model.fp16.safetensors)
 ---> System.InvalidOperationException: ComfyUI execution error: ERROR: Could not detect model type of: D:\Desktop\codeTime\service\StableSwarmUI\Models\Stable-Diffusion\UNet\Kolors\diffusion_pytorch_model.fp16.safetensors
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GetAllImagesForHistory(JToken output, CancellationToken interrupt) in D:\Desktop\codeTime\service\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 451
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in D:\Desktop\codeTime\service\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 382
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.LoadModel(T2IModel model) in D:\Desktop\codeTime\service\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 768
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StableSwarmUI.Backends.BackendHandler.<>c__DisplayClass50_3.<LoadHighestPressureNow>b__13() in D:\Desktop\codeTime\service\StableSwarmUI\src\Backends\BackendHandler.cs:line 1123
02:28:44.206 [Warning] [BackendHandler] backend #0 failed to load model UNet/Kolors/diffusion_pytorch_model.fp16.safetensors
02:28:45.045 [Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
02:29:04.822 [Error] [BackendHandler] Backend request #1 failed: System.InvalidOperationException: All available backends failed to load the model.
   at StableSwarmUI.Backends.BackendHandler.LoadHighestPressureNow(List`1 possible, List`1 available, Action releasePressure, CancellationToken cancel) in D:\Desktop\codeTime\service\StableSwarmUI\src\Backends\BackendHandler.cs:line 1080
   at StableSwarmUI.Backends.BackendHandler.T2IBackendRequest.TryFind() in D:\Desktop\codeTime\service\StableSwarmUI\src\Backends\BackendHandler.cs:line 842
   at StableSwarmUI.Backends.BackendHandler.RequestHandlingLoop() in D:\Desktop\codeTime\service\StableSwarmUI\src\Backends\BackendHandler.cs:line 970
02:29:04.828 [Error] [BackendHandler] Backend request #1 failed: System.InvalidOperationException: All available backends failed to load the model.
   at StableSwarmUI.Backends.BackendHandler.LoadHighestPressureNow(List`1 possible, List`1 available, Action releasePressure, CancellationToken cancel) in D:\Desktop\codeTime\service\StableSwarmUI\src\Backends\BackendHandler.cs:line 1080
   at StableSwarmUI.Backends.BackendHandler.T2IBackendRequest.TryFind() in D:\Desktop\codeTime\service\StableSwarmUI\src\Backends\BackendHandler.cs:line 842
   at StableSwarmUI.Backends.BackendHandler.RequestHandlingLoop() in D:\Desktop\codeTime\service\StableSwarmUI\src\Backends\BackendHandler.cs:line 970

**Comment by mcmonkey4eva** [comment]
Did you miss the readme migration notice? https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#migration-notice
https://github.com/mcmonkeyprojects/SwarmUI/discussions/2

**Comment by atom-fox** [comment]
Yes, I didn't notice this project was migrated. This issue has been resolved: tensorrt needs to be installed using StableSwarmUI/dlbackend/comfy/python_embeded/python.exe
