### ISSUE TITLE
Getting ComfyUI assertion error when generating

### ISSUE THREAD

**Issue by pwilkin** [Stability-AI/StableSwarmUI#436]
Getting an error when generating with ratio 16:9 for SD3, as follows: 

```
> 15:26:07.671 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
> 15:26:07.682 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 151, in recursive_execute
> 15:26:07.683 [Warning] [ComfyUI-0/STDERR]     output_data, output_ui = get_output_data(obj, input_data_all)
> 15:26:07.684 [Warning] [ComfyUI-0/STDERR]                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.685 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 81, in get_output_data
> 15:26:07.685 [Warning] [ComfyUI-0/STDERR]     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> 15:26:07.686 [Warning] [ComfyUI-0/STDERR]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.687 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 74, in map_node_over_list
> 15:26:07.687 [Warning] [ComfyUI-0/STDERR]     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> 15:26:07.688 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.689 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon\SwarmKSampler.py", line 299, in run_sampling
> 15:26:07.689 [Warning] [ComfyUI-0/STDERR]     return self.sample(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, start_at_step, end_at_step, var_seed, var_seed_strength, sigma_max, sigma_min, rho, add_noise, return_with_leftover_noise, previews)
> 15:26:07.690 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.691 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon\SwarmKSampler.py", line 272, in sample
> 15:26:07.691 [Warning] [ComfyUI-0/STDERR]     samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_samples,
> 15:26:07.692 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.693 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\sample.py", line 43, in sample
> 15:26:07.694 [Warning] [ComfyUI-0/STDERR]     samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
> 15:26:07.694 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.695 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 801, in sample
> 15:26:07.695 [Warning] [ComfyUI-0/STDERR]     return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
> 15:26:07.696 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.697 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 703, in sample
> 15:26:07.697 [Warning] [ComfyUI-0/STDERR]     return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
> 15:26:07.698 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.699 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 690, in sample
> 15:26:07.699 [Warning] [ComfyUI-0/STDERR]     output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
> 15:26:07.700 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.700 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 669, in inner_sample
> 15:26:07.701 [Warning] [ComfyUI-0/STDERR]     samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
> 15:26:07.702 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.702 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 574, in sample
> 15:26:07.703 [Warning] [ComfyUI-0/STDERR]     samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
> 15:26:07.704 [Warning] [ComfyUI-0/STDERR]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.704 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
> 15:26:07.705 [Warning] [ComfyUI-0/STDERR]     return func(*args, **kwargs)
> 15:26:07.705 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.706 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\k_diffusion\sampling.py", line 143, in sample_euler
> 15:26:07.707 [Warning] [ComfyUI-0/STDERR]     denoised = model(x, sigma_hat * s_in, **extra_args)
> 15:26:07.708 [Warning] [ComfyUI-0/STDERR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.709 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 297, in __call__
> 15:26:07.710 [Warning] [ComfyUI-0/STDERR]     out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
> 15:26:07.711 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.712 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 656, in __call__
> 15:26:07.713 [Warning] [ComfyUI-0/STDERR]     return self.predict_noise(*args, **kwargs)
> 15:26:07.713 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.714 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 659, in predict_noise
> 15:26:07.715 [Warning] [ComfyUI-0/STDERR]     return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
> 15:26:07.716 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.717 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 277, in sampling_function
> 15:26:07.718 [Warning] [ComfyUI-0/STDERR]     out = calc_cond_batch(model, conds, x, timestep, model_options)
> 15:26:07.719 [Warning] [ComfyUI-0/STDERR]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.719 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\samplers.py", line 226, in calc_cond_batch
> 15:26:07.720 [Warning] [ComfyUI-0/STDERR]     output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
> 15:26:07.721 [Warning] [ComfyUI-0/STDERR]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.722 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\model_base.py", line 114, in apply_model
> 15:26:07.722 [Warning] [ComfyUI-0/STDERR]     model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
> 15:26:07.723 [Warning] [ComfyUI-0/STDERR]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.724 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
> 15:26:07.725 [Warning] [ComfyUI-0/STDERR]     return self._call_impl(*args, **kwargs)
> 15:26:07.725 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.726 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
> 15:26:07.727 [Warning] [ComfyUI-0/STDERR]     return forward_call(*args, **kwargs)
> 15:26:07.727 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.728 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 977, in forward
> 15:26:07.729 [Warning] [ComfyUI-0/STDERR]     return super().forward(x, timesteps, context=context, y=y, control=control)
> 15:26:07.730 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.730 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 952, in forward
> 15:26:07.731 [Warning] [ComfyUI-0/STDERR]     x = self.x_embedder(x) + self.cropped_pos_embed(hw, device=x.device).to(dtype=x.dtype, device=x.device)
> 15:26:07.732 [Warning] [ComfyUI-0/STDERR]                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.733 [Warning] [ComfyUI-0/STDERR]   File "I:\SwarmUI\SwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 859, in cropped_pos_embed
> 15:26:07.734 [Warning] [ComfyUI-0/STDERR]     assert w <= self.pos_embed_max_size, (w, self.pos_embed_max_size)
> 15:26:07.735 [Warning] [ComfyUI-0/STDERR]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 15:26:07.736 [Warning] [ComfyUI-0/STDERR] AssertionError: (210, 192)
> 15:26:07.737 [Warning] [ComfyUI-0/STDERR]
```

**Comment by mcmonkey4eva** [comment]
wrong repo - you want https://github.com/mcmonkeyprojects/SwarmUI

**Comment by pwilkin** [comment]
Sorry, I was sure I was on your repo :/
