### ISSUE TITLE
Unable to load existing ComfyUI

### ISSUE THREAD

**Issue by kungfudante** [Stability-AI/StableSwarmUI#439]
I'm using Ubuntu 22.04.4 LTS, ComfyUI is in /datadisk/ComfyUI/, SwarmUI is in /datadisk/swarmui/SwarmUI/.
I added ComfyUI backend like this:
![image](https://github.com/user-attachments/assets/1a166c89-fcb9-46a9-8ae1-1c18699f3810)
But got error like this:
![image](https://github.com/user-attachments/assets/ab9739de-7de5-4d05-86a0-1f6783127f53)

The output of ` bash launch-linux.sh` is as follow:
```
05:18:35.576 [Init] === SwarmUI v0.9.1.1 Starting at 2024-07-22 05:18:35 ===
05:18:35.632 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
05:18:35.642 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
05:18:35.642 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
05:18:35.642 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
05:18:35.643 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
05:18:35.643 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
05:18:35.687 [Init] Parsing command line...
05:18:35.687 [Init] Loading settings file...
05:18:35.714 [Init] Re-saving settings file...
05:18:35.732 [Init] Applying command line settings...
05:18:35.763 [Init] Prepping options...
05:18:35.766 [Init] Current git commit marked as date 2024-07-19 05:44:18
05:18:35.783 [Init] CPU Cores: 24 | RAM: 216.25 GiB total, 212.45 GiB available
05:18:35.784 [Init] GPU 0: NVIDIA A100 80GB PCIe | Temp 34C | Util 0% GPU, 0% Memory | VRAM 80.00 GiB total, 78.87 GiB free, 270.00 MiB used
05:18:35.942 [Init] Loading models list...
05:18:35.947 [Init] Loading backends...
05:18:35.949 [Init] Loading backends from file...
05:18:35.952 [Init] Initializing backend #1 - ComfyUI Self-Starting...
05:18:35.952 [Init] Prepping API...
05:18:35.954 [Init] Backend request handler loop ready...
05:18:35.955 [Init] Prepping webserver...
fatal: detected dubious ownership in repository at '/datadisk/ComfyUI'
To add an exception for this directory, call:

        git config --global --add safe.directory /datadisk/ComfyUI
05:18:36.094 [Init] Swarm is up to date! You have version 0.9.1.1, and 0.9.1-Beta is the latest.
05:18:36.148 [Init] Scan for web extensions...
05:18:36.152 [Init] Readying extensions for launch...
05:18:36.152 [Init] Launching server...
05:18:36.152 [Init] Starting webserver on http://0.0.0.0:7801
05:18:36.211 [Init] Program is running.
05:18:36.569 [Init] Self-Start ComfyUI-1 on port 7821 is loading...
05:18:36.711 [Init] Launch web browser...
05:18:37.271 [Warning] [ComfyUI-1/STDERR] Traceback (most recent call last):
05:18:37.272 [Warning] [ComfyUI-1/STDERR]   File "/datadisk/ComfyUI/main.py", line 78, in <module>
05:18:37.272 [Warning] [ComfyUI-1/STDERR]     import comfy.utils
05:18:37.272 [Warning] [ComfyUI-1/STDERR]   File "/datadisk/ComfyUI/comfy/utils.py", line 1, in <module>
05:18:37.272 [Warning] [ComfyUI-1/STDERR]     import torch
05:18:37.272 [Warning] [ComfyUI-1/STDERR] ModuleNotFoundError: No module named 'torch'
05:18:37.289 [Info] Self-Start ComfyUI-1 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
05:18:37.290 [Info] Self-Start ComfyUI-1 had errors before shutdown:
[ComfyUI-1/STDERR] Traceback (most recent call last):
[ComfyUI-1/STDERR]   File "/datadisk/ComfyUI/main.py", line 78, in <module>
[ComfyUI-1/STDERR]     import comfy.utils
[ComfyUI-1/STDERR]   File "/datadisk/ComfyUI/comfy/utils.py", line 1, in <module>
[ComfyUI-1/STDERR]     import torch
[ComfyUI-1/STDERR] ModuleNotFoundError: No module named 'torch'

update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/local/share/doc /usr/local/share/doc none bind,ro 0 0): cannot open directory "/usr/local/share": permission denied
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/cups/doc-root /usr/share/cups/doc-root none bind,ro 0 0): cannot write to "/var/lib/snapd/hostfs/usr/share/cups/doc-root" because it would affect the host in "/var/lib/snapd"
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/gimp/2.0/help /usr/share/gimp/2.0/help none bind,ro 0 0): cannot write to "/var/lib/snapd/hostfs/usr/share/gimp/2.0/help" because it would affect the host in "/var/lib/snapd"
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/gtk-doc /usr/share/gtk-doc none bind,ro 0 0): cannot write to "/var/lib/snapd/hostfs/usr/share/gtk-doc" because it would affect the host in "/var/lib/snapd"
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/libreoffice/help /usr/share/libreoffice/help none bind,ro 0 0): cannot write to "/var/lib/snapd/hostfs/usr/share/libreoffice/help" because it would affect the host in "/var/lib/snapd"
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/sphinx_rtd_theme /usr/share/sphinx_rtd_theme none bind,ro 0 0): cannot write to "/var/lib/snapd/hostfs/usr/share/sphinx_rtd_theme" because it would affect the host in "/var/lib/snapd"
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/xubuntu-docs /usr/share/xubuntu-docs none bind,ro 0 0): cannot write to "/var/lib/snapd/hostfs/usr/share/xubuntu-docs" because it would affect the host in "/var/lib/snapd"
MoTTY X11 proxy: No authorisation provided
Error: cannot open display: localhost:11.0
05:19:03.295 [Info] Creating new admin session 'local' for 127.0.0.1 (forwarded-for: <my public IP>)
^C05:39:58.933 [Info] Shutting down...
05:39:58.933 [Info] Backend request handler loop closing...
05:39:58.934 [Error] Error #1 while initializing backend #1 - ComfyUI Self-Starting - will retry
```
I already ran ` git config --global --add safe.directory /datadisk/ComfyUI`
I'm using nginx so that I can access to this from my own device

**Comment by fiftin** [comment]
Hi @kungfudante 
did you fix the issue?

**Comment by mcmonkey4eva** [comment]
Did you miss the readme migration notice? https://github.com/Stability-AI/StableSwarmUI?tab=readme-ov-file#migration-notice
https://github.com/mcmonkeyprojects/SwarmUI/discussions/2

**Comment by kungfudante** [comment]
Hi @fiftin , sry I didn't
Hi @mcmonkey4eva , sry I thought I posted in the new project, actually I deployed the new project, let me post this issue there

**Comment by kungfudante** [comment]
This issue is posted in the new project, please follow-up in https://github.com/mcmonkeyprojects/SwarmUI/issues/89#issue-2428763500
