### ISSUE TITLE
Just got this : which started happing tonight "T2IEngine.cs:line 126"

### ISSUE THREAD

**Issue by jacksteel13** [Stability-AI/StableSwarmUI#45]
I just got this error stating tonight. I am having it create 4 images, and it does about 2-3 then errors. I even disabled one of my backends to see if that was the issue, and I get the same error,

[Error] Internal error processing T2I request: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIAPIAbstractBackend.Generate(T2IParamInput user_input) in C:\Swarm\StableSwarmUI\src\BuiltinExtensions\AutoWebUIBackend\AutoWebUIAPIAbstractBackend.cs:line 98
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages) in C:\Swarm\StableSwarmUI\src\Text2Image\T2IEngine.cs:line 126
 50%|█████████████████████████████████████████

**Comment by jacksteel13** [comment]
I think this only happens when I try to use the image generation url from another computer. When I created images locally, even with all my backends attached, I didn't get any errors. However as soon as I go to another computer, that's when I get the error,

**Comment by mcmonkey4eva** [comment]
That seems to indicate your auto webui backend failed to return an image for a generation request.

You'll be much better off just using the comfy backend, it works a lot better.
