### ISSUE TITLE
All backends failed to load the model.  Type is unset

### ISSUE THREAD

**Issue by XeroCreator** [Stability-AI/StableSwarmUI#462]
I previously used sd3 medium with no issues... but now both 3 and 3.5 give me issues when dropping in models. 
I did my normal thing and reinstalled from scratch using the stableswarmui installer, but after loading in and copying the text encoders and models over, it says type:(unset) on the model
![odd-error-after-generating-an-image-all-available-backends-v0-1ovu2xpkz0yd1](https://github.com/user-attachments/assets/d645da02-4b72-4e14-8123-907e77c22b0d)
 and gives me the error that all backends failed to load the model.
![odd-error-after-generating-an-image-all-available-backends-v0-1c8ycw6tz0yd1](https://github.com/user-attachments/assets/98ba4607-af0e-4fef-8df6-5f338635d685)

I got the models from huggingface, i re-downloaded them to be sure and i still have the same error. 
I believe I'm missing something for the 3.5 models perhaps. 

I'll get the full log when i get home and have time to copy paste it if it's needed.
I saw another issue but mine is a bit different, and simply updating doesn't fix anything.

Tried:
Updating from the batch file and the update and restart button on swarmui.
Re-cloning the repository to another folder.
Re-downloading all models (sd3 med, sd3.5 med, 3.5 large, and 3.5 large turbo.
Redownloaded text encoders and put them in clip folder. 
Restarted pc
Tried the auto installer for swarmui
Sadly no luck. 
Help is appreciated.

**Comment by XeroCreator** [comment]
Log:
2024-10-31 07:14:30.643 [Init] === StableSwarmUI v0.6.4.1 Starting at 2024-10-31 07:14:30 ===
2024-10-31 07:14:30.710 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension...
2024-10-31 07:14:30.716 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension...
2024-10-31 07:14:30.716 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2024-10-31 07:14:30.717 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2024-10-31 07:14:30.717 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2024-10-31 07:14:30.717 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2024-10-31 07:14:30.718 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2024-10-31 07:14:30.736 [Init] Parsing command line...
2024-10-31 07:14:30.737 [Init] Loading settings file...
2024-10-31 07:14:30.756 [Init] Re-saving settings file...
2024-10-31 07:14:30.766 [Init] Applying command line settings...
2024-10-31 07:14:30.854 [Init] Prepping options...
2024-10-31 07:14:30.909 [Init] Current git commit marked as date 2024-06-21 09:26:07
2024-10-31 07:14:30.934 [Init] Loading models list...
2024-10-31 07:14:31.000 [Init] Loading backends...
2024-10-31 07:14:31.001 [Init] Loading backends from file...
2024-10-31 07:14:31.006 [Init] Prepping API...
2024-10-31 07:14:31.006 [Init] Initializing backend #0 - ComfyUI Self-Starting...
2024-10-31 07:14:31.006 [Init] Backend request handler loop ready...
2024-10-31 07:14:31.007 [Init] Prepping webserver...
2024-10-31 07:14:31.033 [Init] CPU Cores: 32 | RAM: 63.75 GiB total, 47.05 GiB available
2024-10-31 07:14:31.033 [Init] GPU 0: NVIDIA GeForce RTX 4090 | Temp 49C | Util 34% GPU, 6% Memory | VRAM 23.99 GiB total, 18.92 GiB free, 4.66 GiB used
2024-10-31 07:14:31.084 [Init] Swarm is up to date! Version 0.6.4.1 is the latest.
2024-10-31 07:14:31.098 [Init] Scan for web extensions...
2024-10-31 07:14:31.099 [Init] Readying extensions for launch...
2024-10-31 07:14:31.099 [Init] Launching server...
2024-10-31 07:14:31.100 [Init] Starting webserver on http://localhost:7801
2024-10-31 07:14:31.122 [Init] Program is running.
2024-10-31 07:14:31.637 [Init] Launch web browser...
2024-10-31 07:14:31.675 [Info] Self-Start ComfyUI (Git Pull) exited properly.
2024-10-31 07:14:31.687 [Info] Self-Start comfy node pull (ComfyUI-SAI_API) exited properly.
2024-10-31 07:14:31.708 [Info] Self-Start comfy node pull (sd-dynamic-thresholding) exited properly.
2024-10-31 07:14:32.119 [Info] Creating new admin session 'local' for ::1
2024-10-31 07:14:32.177 [Info] Self-Start comfy node pull (ComfyUI-SAI_API) exited properly.
2024-10-31 07:14:32.209 [Info] Self-Start comfy node pull (sd-dynamic-thresholding) exited properly.
2024-10-31 07:14:32.232 [Init] Self-Start ComfyUI-0 on port 7821 is loading...
2024-10-31 07:14:40.372 [Init] Self-Start ComfyUI-0 on port 7821 started.
2024-10-31 07:16:59.945 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
2024-10-31 07:16:59.946 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
2024-10-31 07:16:59.947 [Warning] ComfyUI-0 on port 7821 stderr:     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-10-31 07:16:59.947 [Warning] ComfyUI-0 on port 7821 stderr:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:16:59.948 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
2024-10-31 07:16:59.948 [Warning] ComfyUI-0 on port 7821 stderr:     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-10-31 07:16:59.949 [Warning] ComfyUI-0 on port 7821 stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:16:59.949 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
2024-10-31 07:16:59.950 [Warning] ComfyUI-0 on port 7821 stderr:     process_inputs(input_dict, i)
2024-10-31 07:16:59.950 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
2024-10-31 07:16:59.951 [Warning] ComfyUI-0 on port 7821 stderr:     results.append(getattr(obj, func)(**inputs))
2024-10-31 07:16:59.952 [Warning] ComfyUI-0 on port 7821 stderr:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:16:59.953 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 64, in encode
2024-10-31 07:16:59.953 [Warning] ComfyUI-0 on port 7821 stderr:     tokens = clip.tokenize(text)
2024-10-31 07:16:59.954 [Warning] ComfyUI-0 on port 7821 stderr:              ^^^^^^^^^^^^^
2024-10-31 07:16:59.954 [Warning] ComfyUI-0 on port 7821 stderr: AttributeError: 'NoneType' object has no attribute 'tokenize'
2024-10-31 07:16:59.954 [Warning] ComfyUI-0 on port 7821 stderr: 
2024-10-31 07:17:13.146 [Info] User local requested 1 image with model 'sd3.5_large.safetensors'...
2024-10-31 07:17:15.497 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last):
2024-10-31 07:17:15.497 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 323, in execute
2024-10-31 07:17:15.498 [Warning] ComfyUI-0 on port 7821 stderr:     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-10-31 07:17:15.499 [Warning] ComfyUI-0 on port 7821 stderr:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.499 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 198, in get_output_data
2024-10-31 07:17:15.500 [Warning] ComfyUI-0 on port 7821 stderr:     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-10-31 07:17:15.500 [Warning] ComfyUI-0 on port 7821 stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.501 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 169, in _map_node_over_list
2024-10-31 07:17:15.502 [Warning] ComfyUI-0 on port 7821 stderr:     process_inputs(input_dict, i)
2024-10-31 07:17:15.502 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 158, in process_inputs
2024-10-31 07:17:15.503 [Warning] ComfyUI-0 on port 7821 stderr:     results.append(getattr(obj, func)(**inputs))
2024-10-31 07:17:15.503 [Warning] ComfyUI-0 on port 7821 stderr:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.503 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 284, in decode
2024-10-31 07:17:15.504 [Warning] ComfyUI-0 on port 7821 stderr:     images = vae.decode(samples["samples"])
2024-10-31 07:17:15.504 [Warning] ComfyUI-0 on port 7821 stderr:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.505 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\sd.py", line 340, in decode
2024-10-31 07:17:15.505 [Warning] ComfyUI-0 on port 7821 stderr:     out = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
2024-10-31 07:17:15.505 [Warning] ComfyUI-0 on port 7821 stderr:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.506 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\models\autoencoder.py", line 137, in decode
2024-10-31 07:17:15.506 [Warning] ComfyUI-0 on port 7821 stderr:     x = self.decoder(z, **kwargs)
2024-10-31 07:17:15.507 [Warning] ComfyUI-0 on port 7821 stderr:         ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.507 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
2024-10-31 07:17:15.508 [Warning] ComfyUI-0 on port 7821 stderr:     return self._call_impl(*args, **kwargs)
2024-10-31 07:17:15.508 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.510 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
2024-10-31 07:17:15.511 [Warning] ComfyUI-0 on port 7821 stderr:     return forward_call(*args, **kwargs)
2024-10-31 07:17:15.511 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.512 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 625, in forward
2024-10-31 07:17:15.512 [Warning] ComfyUI-0 on port 7821 stderr:     h = self.conv_in(z)
2024-10-31 07:17:15.513 [Warning] ComfyUI-0 on port 7821 stderr:         ^^^^^^^^^^^^^^^
2024-10-31 07:17:15.513 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
2024-10-31 07:17:15.514 [Warning] ComfyUI-0 on port 7821 stderr:     return self._call_impl(*args, **kwargs)
2024-10-31 07:17:15.514 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.515 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
2024-10-31 07:17:15.515 [Warning] ComfyUI-0 on port 7821 stderr:     return forward_call(*args, **kwargs)
2024-10-31 07:17:15.515 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.516 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\ops.py", line 98, in forward
2024-10-31 07:17:15.517 [Warning] ComfyUI-0 on port 7821 stderr:     return super().forward(*args, **kwargs)
2024-10-31 07:17:15.517 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.518 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
2024-10-31 07:17:15.519 [Warning] ComfyUI-0 on port 7821 stderr:     return self._conv_forward(input, self.weight, self.bias)
2024-10-31 07:17:15.519 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.520 [Warning] ComfyUI-0 on port 7821 stderr:   File "S:\AI ART\SD 3.5\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
2024-10-31 07:17:15.520 [Warning] ComfyUI-0 on port 7821 stderr:     return F.conv2d(input, weight, bias, self.stride,
2024-10-31 07:17:15.521 [Warning] ComfyUI-0 on port 7821 stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-31 07:17:15.521 [Warning] ComfyUI-0 on port 7821 stderr: RuntimeError: Given groups=1, weight of size [512, 16, 3, 3], expected input[1, 4, 32, 32] to have 16 channels, but got 4 channels instead
2024-10-31 07:17:15.522 [Warning] ComfyUI-0 on port 7821 stderr: 
2024-10-31 07:17:15.589 [Error] [BackendHandler] backend #0 failed to load model with error: System.AggregateException: One or more errors occurred. (ComfyUI execution error: Given groups=1, weight of size [512, 16, 3, 3], expected input[1, 4, 32, 32] to have 16 channels, but got 4 channels instead)
 ---> System.InvalidOperationException: ComfyUI execution error: Given groups=1, weight of size [512, 16, 3, 3], expected input[1, 4, 32, 32] to have 16 channels, but got 4 channels instead
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GetAllImagesForHistory(JToken output, CancellationToken interrupt) in S:\AI ART\SD 3.5\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 451
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in S:\AI ART\SD 3.5\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 382
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.LoadModel(T2IModel model) in S:\AI ART\SD 3.5\StableSwarmUI\src\BuiltinExtensions\ComfyUIBackend\ComfyUIAPIAbstractBackend.cs:line 768
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StableSwarmUI.Backends.BackendHandler.<>c__DisplayClass50_3.<LoadHighestPressureNow>b__13() in S:\AI ART\SD 3.5\StableSwarmUI\src\Backends\BackendHandler.cs:line 1117
2024-10-31 07:17:15.591 [Warning] [BackendHandler] backend #0 failed to load model sd3.5_large.safetensors
2024-10-31 07:17:16.171 [Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
2024-10-31 07:17:16.173 [Error] [BackendHandler] Backend request #1 failed: System.InvalidOperationException: All available backends failed to load the model.
   at StableSwarmUI.Backends.BackendHandler.LoadHighestPressureNow(List`1 possible, List`1 available, Action releasePressure, CancellationToken cancel) in S:\AI ART\SD 3.5\StableSwarmUI\src\Backends\BackendHandler.cs:line 1080
   at StableSwarmUI.Backends.BackendHandler.T2IBackendRequest.TryFind() in S:\AI ART\SD 3.5\StableSwarmUI\src\Backends\BackendHandler.cs:line 842
   at StableSwarmUI.Backends.BackendHandler.RequestHandlingLoop() in S:\AI ART\SD 3.5\StableSwarmUI\src\Backends\BackendHandler.cs:line 970
2024-10-31 07:17:16.174 [Error] [BackendHandler] Backend request #1 failed: System.InvalidOperationException: All available backends failed to load the model.
   at StableSwarmUI.Backends.BackendHandler.LoadHighestPressureNow(List`1 possible, List`1 available, Action releasePressure, CancellationToken cancel) in S:\AI ART\SD 3.5\StableSwarmUI\src\Backends\BackendHandler.cs:line 1080
   at StableSwarmUI.Backends.BackendHandler.T2IBackendRequest.TryFind() in S:\AI ART\SD 3.5\StableSwarmUI\src\Backends\BackendHandler.cs:line 842
   at StableSwarmUI.Backends.BackendHandler.RequestHandlingLoop() in S:\AI ART\SD 3.5\StableSwarmUI\src\Backends\BackendHandler.cs:line 970

**Comment by kalebbroo** [comment]
StableSwarmUI is the old unmaintained repo. You need to use  
https://github.com/mcmonkeyprojects/SwarmUI

The developer quit working for Stability and moved his project over to his personal page.
