### ISSUE TITLE
christoph_aesthetic.py assumes pytorch_lightning is available

### ISSUE THREAD

**Issue by olivierlacan** [Stability-AI/StableSwarmUI#54]
But `pytorch_lightning` is listed in the [requirements.txt within the BuiltinExtensions/Scorer](https://github.com/olivierlacan/StableSwarmUI/blob/0501a42d4723dd122f2fd4c6fa6a96e139477048/src/BuiltinExtensions/Scorers/requirements.txt#L2-L2) directory, not in the top-level requirements.txt.

That doesn't get `pip install`-ed by the setup scripts as far as I can tell. Should it be? 

I note that dlbackend/ComfyUi also doesn't get `pip install -r requirements.txt` called on it either so maybe that's expected? Should it be added to the installation instructions in the README, then? 

My first run fresh from the install script and after installing the dependencies for ComfyUI only resulted in this error and stacktrace toward the end of the generation process: 

```
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 59121)
Traceback (most recent call last):
  File "/Users/olivierlacan/.pyenv/versions/3.11.4/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/olivierlacan/.pyenv/versions/3.11.4/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/Users/olivierlacan/.pyenv/versions/3.11.4/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/olivierlacan/.pyenv/versions/3.11.4/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/Users/olivierlacan/.pyenv/versions/3.11.4/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/Users/olivierlacan/.pyenv/versions/3.11.4/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/Users/olivierlacan/Development/oss/StableSwarmUI/src/BuiltinExtensions/Scorers/scorer_engine.py", line 137, in do_POST
    scorer.load()
  File "/Users/olivierlacan/Development/oss/StableSwarmUI/src/BuiltinExtensions/Scorers/scorer_engine.py", line 90, in load
    from christoph_aesthetic import AestheticPredictor
  File "/Users/olivierlacan/Development/oss/StableSwarmUI/src/BuiltinExtensions/Scorers/christoph_aesthetic.py", line 5, in <module>
    import pytorch_lightning as pl
ModuleNotFoundError: No module named 'pytorch_lightning'
----------------------------------------
16:54:55.851 [Error] ScorerExtension error: failed: No module named 'pytorch_lightning'
16:54:55.862 [Error] Internal error processing T2I request: System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'value'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at StableSwarmUI.Builtin_ScorersExtension.ScorersExtension.DoScore(Image image, String prompt, String scorer) in /Users/olivierlacan/Development/oss/StableSwarmUI/src/BuiltinExtensions/Scorers/ScorersExtension.cs:line 117
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at StableSwarmUI.Builtin_ScorersExtension.ScorersExtension.PostGenEvent(PostGenerationEventParams p) in /Users/olivierlacan/Development/oss/StableSwarmUI/src/BuiltinExtensions/Scorers/ScorersExtension.cs:line 134
   at StableSwarmUI.Text2Image.T2IEngine.<>c__DisplayClass8_1.<CreateImageTask>g__handleImage|1(Image img) in /Users/olivierlacan/Development/oss/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 128
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, CancellationToken interrupt) in /Users/olivierlacan/Development/oss/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 194
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in /Users/olivierlacan/Development/oss/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 366
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages) in /Users/olivierlacan/Development/oss/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 148
```

**Comment by mcmonkey4eva** [comment]
This is mentioned in the readme for it: https://github.com/Stability-AI/StableSwarmUI/blob/master/src/BuiltinExtensions/Scorers/README.md

That's an artifact of Swarm's Alpha state. That's meant to fully self-automate away, but hasn't been yet, and kinda just presumes you have a working python install and are willing to pip install the reqs.

It's likely going to be entirely replaced in the future, pooooooosssibly even a non-python approach.

**Comment by olivierlacan** [comment]
Thanks, missed that README. 

I ended up setting up pyenv with pipenv. Didn't really want to bother with Anaconda/Miniconda. Worked out pretty well since `pyenv shell` gives me a virtual environment that is scoped to the top-level repo (StableSwarmUI) so I can share installed dependencies. 

I think it's fine to have multiple steps but maybe a hint in the top-level README's install sections would help discovery until you simplify things? It's a weird error to recover from especially if you're not familiar with Python stack traces. 

I'll note the Linux install script [does it for Comfy](https://github.com/Stability-AI/StableSwarmUI/blob/0d1e9fccde96069b822d10d124649ede8def56ec/launchtools/comfy-install-linux.sh#L13) so it doesn't feel like a stretch to have it swing by Scorers as well. 😸
