### ISSUE TITLE
A11 by URL backend error

### ISSUE THREAD

**Issue by enslaved2die** [Stability-AI/StableSwarmUI#58]
Im trying to add a Auto111 WebUI Backend running on a Mac but I get this error:

` Final error (4) while initializing backend #1 - Auto1111 SD-WebUI API By URL, giving up: System.InvalidOperationException: Failed to read JSON '{"detail":"Not Found"}' with message: Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.
   at StableSwarmUI.Backends.NetworkBackendUtils.Parse[JType](HttpResponseMessage message) in C:\Users\"name"\Desktop\StableSwarm\StableSwarmUI\src\Backends\NetworkBackendUtils.cs:line 77
   at StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIAPIAbstractBackend.SendGet[JType](String url) in C:\Users\"name"\Desktop\StableSwarm\StableSwarmUI\src\BuiltinExtensions\AutoWebUIBackend\AutoWebUIAPIAbstractBackend.cs:line 106
   at StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIAPIAbstractBackend.InitInternal(Boolean ignoreWebError) in C:\Users\"name"\Desktop\StableSwarm\StableSwarmUI\src\BuiltinExtensions\AutoWebUIBackend\AutoWebUIAPIAbstractBackend.cs:line 53`
   
 Any ideas what to do?

**Comment by mcmonkey4eva** [comment]
Looks like probably you forgot to launch auto webui with `--api`?

Auto replied to an API request with `{"detail":"Not Found"}`, and swarm failed to load the backend because of that.
