### ISSUE TITLE
ComfyUI cannot load the models

### ISSUE THREAD

**Issue by pixelass** [Stability-AI/StableSwarmUI#8]
1. I used the installer.bat.
2. I ran the install (no error)
3. the models show up in th model tab 
4. When I atempt to load a model I get an error (tried sdxl-1.0 and the 1.5-pruned) 

> models cannot be selected in ComfyUI (no dropdown)  
> models are visiblew in the "Generate section"

![image](https://github.com/Stability-AI/StableSwarmUI/assets/1148334/203ec73c-554d-4e13-adaa-4b02579615e2)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/1148334/ed9743c4-703e-4b15-a501-05872db8ed16)
![image](https://github.com/Stability-AI/StableSwarmUI/assets/1148334/9436a028-42ee-489b-83d1-1e873d989b31)

**Error:**

```
21:52:43.523 [Info] Creating new admin session for ::1
21:54:11.133 [Error] ComfyUI error: {
  "error": {
    "type": "prompt_outputs_failed_validation",
    "message": "Prompt outputs failed validation",
    "details": "",
    "extra_info": {}
  },
  "node_errors": {
    "4": {
      "errors": [
        {
          "type": "value_not_in_list",
          "message": "Value not in list",
          "details": "ckpt_name: 'OfficialStableDiffusion\\sd_xl_base_1.0.safetensors' not in []",
          "extra_info": {
            "input_name": "ckpt_name",
            "input_config": [
              []
            ],
            "received_value": "OfficialStableDiffusion\\sd_xl_base_1.0.safetensors"
          }
        }
      ],
      "dependent_outputs": [
        "9"
      ],
      "class_type": "CheckpointLoaderSimple"
    }
  }
}
21:54:11.134 [Warning] [BackendHandler] backend #0 failed to load model OfficialStableDiffusion/sd_xl_base_1.0.safetensors
21:54:11.134 [Warning] [BackendHandler] All backends failed to load the model! Cannot generate anything.
21:54:11.135 [Error] [BackendHandler] Backend request #1 failed: System.InvalidOperationException: All available backends failed to load the model.
   at StableSwarmUI.Backends.BackendHandler.LoadHighestPressureNow(List`1 possible, List`1 available, Action ReleasePressure, CancellationToken cancel) in C:\Users\xxxxx\StableSwarmUI\src\Backends\BackendHandler.cs:line 574
   at StableSwarmUI.Backends.BackendHandler.GetNextT2IBackend(TimeSpan maxWait, T2IModel model, Func`2 filter, Session session, Action notifyWillLoad, CancellationToken cancel) in C:\Users\xxxxx\StableSwarmUI\src\Backends\BackendHandler.cs:line 529

```

**Comment by pixelass** [comment]
I tired deleting the generated folders and running the install again

**Error:**

```
  8% 18825 - ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\include\ATen\ops\range.h22:17:24.292 [Error] [WebAPI] Error handling API request '/API/ListBackends': Request input has unknown session id
```_

**Comment by mcmonkey4eva** [comment]
Try pulling latest commit, already pushed a fix that's probably for the same issue

**Comment by pixelass** [comment]
thx,It just works :)
