### ISSUE TITLE
Backend error after second run of Colab Notebook from Google Drive

### ISSUE THREAD

**Issue by rocketpal** [Stability-AI/StableSwarmUI#89]
I already installed SwarmUI with comfy backend to my Google Drive.

After each SwarmUI start I see this error 

`11:37:09.945 [Warning] ComfyUI start script is '', which looks wrong - did you forget to append 'main.py' on the end?
11:37:09.960 [Error] Failed to auto-update comfy backend: System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUISelfStartBackend.Init() in /content/drive/MyDrive/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUISelfStartBackend.cs:line 107
11:37:42.689 [Init] Scan for web extensions...
11:37:46.366 [Init] Readying extensions for launch...
11:37:46.367 [Init] Launching server...
11:37:46.367 [Init] Starting webserver on http://localhost:7801/`

and backend eror in UI. 
I solved that problem by specifying main.py path (/content/drive/MyDrive/StableSwarmUI/dlbackend/ComfyUI/main.py) in SwarmUI settings. But I have to do that every SwarmUI start which is not convenient. How could I solve this issue?

**Comment by mcmonkey4eva** [comment]
That's... entirely wrong. What? That sounds like either

- A: You've somehow customized/modified the backend in a way that broke it, or
- B: Something is wrong with file access or saving.

When running properly, Swarm will automatically save any backend settings edits you make and preserve them to the next restart. Nothing should change itself nor forget edits made.

**Comment by rocketpal** [comment]
Agreed, but that's exactly what happened, and time to time what is also quite strange. I'm not a programmer, so please let me know where I went wrong:

I installed everything on my Google Drive.
After the first start, I installed all the dependencies again:

```
!apt update
!apt install dotnet-sdk-7.0 git
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb
```

I also added the following:

```
requirements_file_path = "/content/drive/MyDrive/StableSwarmUI/dlbackend/ComfyUI/requirements.txt"
!pip install -r "{requirements_file_path}"
```

Because, in another way, Comfy just doesn't work. And as I just noticed, is it possibly because I'm also cloning the repository every time?

**Comment by mcmonkey4eva** [comment]
wh... why... why have you done any of that?
Don't do any of that.

My recommendation:
Nuke your customizations and your current install folder(s), load up the colab in the readme, use it as prescribed and don't muck with the code. It works. It doesn't self-delete settings. It doesn't require any coding or command-hacking.

**Comment by rocketpal** [comment]
> wh... why... why have you done any of that? Don't do any of that.
> 
> My recommendation: Nuke your customizations and your current install folder(s), load up the colab in the readme, use it as prescribed and don't muck with the code. It works. It doesn't self-delete settings. It doesn't require any coding or command-hacking.

Thanks for you kind reply. But do you really think I had the desire to dig into all of this when there's a ready-to-use notebook? It doesn't work. Please, could you try to be a little less contemptuous and install SwarmUI in Google Drive (with notebook in readme), then restart the session, and you'll see the 'backend error'.  

`=16:28:46.082 [Init] Self-Start ComfyUI on port 7821 is loading...
Traceback (most recent call last):
  File "/content/drive/MyDrive/StableSwarmUI/dlbackend/ComfyUI/main.py", line 66, in <module>
    import comfy.utils
  File "/content/drive/MyDrive/StableSwarmUI/dlbackend/ComfyUI/comfy/utils.py", line 5, in <module>
    import safetensors.torch
ModuleNotFoundError: No module named 'safetensors'
=16:28:58.033 [Info] Self-Start ComfyUI on port 7821 exited.
16:28:58.056 [Init] Scan for web extensions...
16:29:01.603 [Init] Readying extensions for launch...
16:29:01.604 [Init] Launching server...
16:29:01.604 [Init] Starting webserver on http://localhost:7801/
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {b3491ed4-acab-48d9-b1b9-66aa83d94ff7} may be persisted to storage in unencrypted form.
16:29:01.697 [Init] Program is running.
2023-09-04T16:29:01Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2023-09-04T16:29:01Z INF Requesting new quick Tunnel on trycloudflare.com...
2023-09-04T16:29:04Z INF +--------------------------------------------------------------------------------------------+
2023-09-04T16:29:04Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2023-09-04T16:29:04Z INF |  https://gras-ham-industry-contemporary.trycloudflare.com/                                  |
2023-09-04T16:29:04Z INF +--------------------------------------------------------------------------------------------+
2023-09-04T16:29:04Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2023-09-04T16:29:04Z INF Version 2023.8.2
2023-09-04T16:29:04Z INF GOOS: linux, GOVersion: go1.20.6, GoArch: amd64
2023-09-04T16:29:04Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:7801/]
2023-09-04T16:29:04Z INF Generated Connector ID: 2e7150da-f74b-4bd0-8524-3d1934901cf6
2023-09-04T16:29:04Z INF cloudflared will not automatically update if installed by a package manager.
2023-09-04T16:29:04Z INF Initial protocol quic
2023-09-04T16:29:04Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2023-09-04T16:29:04Z INF ICMP proxy will use :: as source for IPv6
2023-09-04T16:29:04Z INF Starting metrics server on 127.0.0.1:36353/metrics
2023/09/04 16:29:04 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023-09-04T16:29:04Z INF Registered tunnel connection connIndex=0 connection=271c1031-8051-4fdb-ab58-5b4317588ca2 event=0 ip=198.41.192.107 location=kul01 protocol=quic
2023-09-04T16:29:21Z ERR  error="stream 245 canceled by remote with error code 0" cfRay=80179c4e0086093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 245 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/site.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 241 canceled by remote with error code 0" cfRay=80179c4e008a093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 241 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/params.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 121 canceled by remote with error code 0" cfRay=80179c48942a093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 121 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/css/select2_bootstrap.min.css event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 137 canceled by remote with error code 0" cfRay=80179c489426093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 137 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/css/genpage.css?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 273 canceled by remote with error code 0" cfRay=80179c4e10a1093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 273 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/ExtensionFile/GridGeneratorExtension/Assets/grid_gen.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 253 canceled by remote with error code 0" cfRay=80179c4e0087093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 253 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/util.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 257 canceled by remote with error code 0" cfRay=80179c4e008f093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 257 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/backends.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 269 canceled by remote with error code 0" cfRay=80179c4e0097093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 269 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/ExtensionFile/ComfyUIBackendExtension/Assets/comfy_workflow_editor_helper.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 117 canceled by remote with error code 0" cfRay=80179c489431093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 117 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/jquery.min.js event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 261 canceled by remote with error code 0" cfRay=80179c4e0089093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 261 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/models.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 249 canceled by remote with error code 0" cfRay=80179c4e008d093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 249 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/main.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 281 canceled by remote with error code 0" cfRay=80179c4e0093093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR  error="stream 185 canceled by remote with error code 0" cfRay=80179c488423093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 281 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/browsers.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR Request failed error="stream 185 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/css/bootstrap.min.css event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 129 canceled by remote with error code 0" cfRay=80179c489427093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR  error="stream 277 canceled by remote with error code 0" cfRay=80179c4e0095093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 277 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/presets.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR Request failed error="stream 129 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/css/select2.min.css event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 145 canceled by remote with error code 0" cfRay=80179c489428093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 145 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/bootstrap.min.js event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 149 canceled by remote with error code 0" cfRay=80179c489438093b-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 149 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/select2.min.js event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 201 canceled by remote with error code 0" cfRay=80179c4cd04ec616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 201 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/site.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 197 canceled by remote with error code 0" cfRay=80179c4cd050c616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 197 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/params.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 205 canceled by remote with error code 0" cfRay=80179c4cd052c616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 205 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/util.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 229 canceled by remote with error code 0" cfRay=80179c4cf060c616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 229 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/main.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 169 canceled by remote with error code 0" cfRay=80179c48d5d6c616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 169 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/css/select2_bootstrap.min.css event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 165 canceled by remote with error code 0" cfRay=80179c48d5d2c616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 165 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/css/bootstrap.min.css event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 221 canceled by remote with error code 0" cfRay=80179c4cd04cc616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 221 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/browsers.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 237 canceled by remote with error code 0" cfRay=80179c48f5e7c616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 237 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/select2.min.js event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 177 canceled by remote with error code 0" cfRay=80179c48d5cdc616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 177 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/bootstrap.min.js event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 209 canceled by remote with error code 0" cfRay=80179c4ce055c616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 209 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/ExtensionFile/ComfyUIBackendExtension/Assets/comfy_workflow_editor_helper.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:21Z ERR  error="stream 285 canceled by remote with error code 0" cfRay=80179c4cd04dc616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:21Z ERR Request failed error="stream 285 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/genpage/presets.js?vary=0.5.4.0 event=0 ip=198.41.192.107 type=http
2023-09-04T16:29:22Z ERR  error="stream 181 canceled by remote with error code 0" cfRay=80179c48e5e1c616-SEA event=1 originService=http://localhost:7801/
2023-09-04T16:29:22Z ERR Request failed error="stream 181 canceled by remote with error code 0" connIndex=0 dest=https://gras-ham-industry-contemporary.trycloudflare.com/js/jquery.min.js event=0 ip=198.41.192.107 type=http
16:29:23.759 [Info] Creating new admin session for 127.0.0.1
16:29:24.438 [Error] [WebAPI] Error handling API request '/API/TriggerRefresh': Request input has unknown session id
16:29:24.883 [Info] Creating new admin session for 127.0.0.1`

**Comment by mcmonkey4eva** [comment]
I did test colab on google drive, with stopping and restarting it in the UI, and it worked when I did.
What I didn't think to test was fully disabling the runtime, closing colab, and opening an entirely new session.

The errors you originally reported are still not an issue, but the new error you posted does appear to occur in my own testing - it looks like Google Drive is unwilling to store the ComfyUI `venv` folder which contains necessary modules.

No offense or contempt was intended. Your original error was caused by your modifications to the notebook, I was not able to replicate any issue until you specified further now.

Adding a cell of `!pip install -r $SWARMPATH/StableSwarmUI/dlbackend/ComfyUI/requirements.txt` and running it fixes it and allows it to run as normal.

It's extremely odd that Colab refused to save venv files into drive - I'd argue that this is technically a bug with Google's server software rather than a bug with Swarm, as it's temporarily storing files in drive as far as the VM can see, but never actually synchronizing it to long-term storage.

Regardless, I've pushed an update that will automatically execute the backup install when needed for colab+drive usage. This now works flawlessly in my testing across a full colab runtime replacement (other than the network conn through trycloudflare being slow and silly as usual).

**Comment by rocketpal** [comment]
> 

The irony is that my 'code modification' was literally the same as what you suggested.

```
requirements_file_path = "/content/drive/MyDrive/StableSwarmUI/dlbackend/ComfyUI/requirements.txt"
!pip install -r "{requirements_file_path}"

```

I haven't changed anything else. The error I described in the issue occurs randomly, to be precise, I'll repeat, with only one aforementioned code modification. I haven't encountered it lately; perhaps this bug won't occur anymore, but time will tell.
