### ISSUE TITLE
Install issue on linux

### ISSUE THREAD

**Issue by the-dusky** [Stability-AI/StableSwarmUI#9]
I am getting the following error when I run /launch-linux.sh

```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'http://localhost:7801/Install' with working directory '/home/ubuntu/StableSwarmUI'. No such file or directory at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, ...
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at StableSwarmUI.Core.Program.Main(String[] args) in /home/ubuntu/StableSwarmUI/src/Core/Program.cs:line 123
./launch-linux.sh: line 13:  6339 Aborted                 (core dumped) dotnet src/bin/live_release/StableSwarmUI.dll $@
```

Any suggestions?

**Comment by YousufSSyed** [comment]
I also got this issue.

**Comment by mcmonkey4eva** [comment]
ooh, does the web launch in a headless env cause a crash?

**Comment by mcmonkey4eva** [comment]
I added an error handler, so it'll just complain in console and then proceed as normal.

The error message also now says how to get rid of the error message too (ie switch LaunchMode to none).
